# coding: utf-8

"""
    API Docs

    API Documentation to interact with

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class SaveVoiceMessageRequest(BaseModel):
    """
    SaveVoiceMessageRequest
    """ # noqa: E501
    project_id: StrictStr
    chat_id: StrictStr
    message: StrictStr
    response: Optional[StrictStr] = None
    user_name: StrictStr
    user_id: StrictStr
    message_type: StrictStr
    agent_id: Optional[StrictStr] = None
    agent_name: Optional[StrictStr] = None
    conversation_id: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["project_id", "chat_id", "message", "response", "user_name", "user_id", "message_type", "agent_id", "agent_name", "conversation_id"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SaveVoiceMessageRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if response (nullable) is None
        # and model_fields_set contains the field
        if self.response is None and "response" in self.model_fields_set:
            _dict['response'] = None

        # set to None if agent_id (nullable) is None
        # and model_fields_set contains the field
        if self.agent_id is None and "agent_id" in self.model_fields_set:
            _dict['agent_id'] = None

        # set to None if agent_name (nullable) is None
        # and model_fields_set contains the field
        if self.agent_name is None and "agent_name" in self.model_fields_set:
            _dict['agent_name'] = None

        # set to None if conversation_id (nullable) is None
        # and model_fields_set contains the field
        if self.conversation_id is None and "conversation_id" in self.model_fields_set:
            _dict['conversation_id'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SaveVoiceMessageRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "project_id": obj.get("project_id"),
            "chat_id": obj.get("chat_id"),
            "message": obj.get("message"),
            "response": obj.get("response"),
            "user_name": obj.get("user_name"),
            "user_id": obj.get("user_id"),
            "message_type": obj.get("message_type"),
            "agent_id": obj.get("agent_id"),
            "agent_name": obj.get("agent_name"),
            "conversation_id": obj.get("conversation_id")
        })
        return _obj


