import typing as t

import pytest
from exobrain.actions.schemas.action_data import ActionData

# fmt: off

ACTION_DATA_LIST = [
    {
        "actionSettings": {
            "CO2_PER_KG": {"choice": True, "defaultValue": "CO2_KG", "name": "CO2_PER_KG"},
            "D_KM": {"choice": True, "defaultValue": "KM", "name": "DISTANCE_KM"},
            "FCD_DLT": {"choice": False, "defaultValue": "Primary", "name": "FCD_DEPLOYMENT_LOCATION_TYPE"},
            "FCD_DT": {"choice": True, "defaultValue": "FCD_ALGO_FORECAST", "name": "FCD_DEMAND_TYPE"},
            "FCD_FCU": {"choice": True, "defaultValue": "FCD_ALGO_UNIT", "name": "FCD_FREIGHT_COST_UNIT"},
            "FCD_GC": {"choice": False, "defaultValue": "GLOBAL_COVERAGE", "name": "FCD_GLOBAL_COVERAGE_NAME"},
            "FCD_GCSC": {"choice": True, "defaultValue": "FCD_ALGO_DOS", "name": "FCD_GLOBAL_COVERAGE_SORTING_CRITERIA"},
            "FCD_GMDOS": {"choice": False, "defaultValue": 20, "name": "FCD_GLOBAL_MINIMUM_DOS", "type": "NUMBER"},
            "FCD_GMQ": {"choice": False, "defaultValue": 0, "name": "FCD_GLOBAL_MINIMUM_QUANTITY", "type": "NUMBER"},
            "FCD_LLC": {"choice": False, "defaultValue": "LOCAL_LOW_COVERAGE", "name": "FCD_LOCAL_LOW_COVERAGE_NAME"},
            "FCD_LLCSC": {"choice": True, "defaultValue": "FCD_ALGO_DOS", "name": "FCD_LOCAL_LOW_COVERAGE_SORTING_CRITERIA"},
            "FCD_LMDOS": {"choice": False, "defaultValue": 10, "name": "FCD_LOCAL_MINIMUM_DOS", "type": "NUMBER"},
            "FCD_LS": {"choice": False, "defaultValue": "LOCAL_STOCKOUT", "name": "FCD_LOCAL_STOCKOUT_NAME"},
            "FCD_LSSC": {"choice": True, "defaultValue": "FCD_ALGO_DOS", "name": "FCD_LOCAL_STOCKOUT_SORTING_CRITERIA"},
            "FCD_MAX_DOS": {"choice": False, "defaultValue": 100, "name": "MAXIMUM_DOS_TARGET", "type": "NUMBER"},
            "FCD_NGC": {"choice": False, "defaultValue": "NOT_GLOBAL_COVERAGE", "name": "FCD_NOT_GLOBAL_COVERAGE_NAME"},
            "FCD_NGCSC": {"choice": True, "defaultValue": "FCD_ALGO_DOS", "name": "FCD_NOT_GLOBAL_COVERAGE_SORTING_CRITERIA"},
            "FCD_SI": {
                "choice": False,
                "defaultValue": 70,
                "name": "FCD_DESTINATION_SORTING_IMPORTANCE_CURRENT_PERCENTAGE",
                "type": "NUMBER",
            },
            "FCD_SP": {"choice": True, "defaultValue": "FCD_ALGO_LOWEST", "name": "FCD_SORTING_PRIORITIZATION"},
            "T_DAYS": {"choice": True, "defaultValue": "DAYS", "name": "TIME_DAYS"},
            "V_CO2": {"choice": True, "defaultValue": "M_SQUARE_PER_M_CUBE", "name": "VOLUME_CO2"},
            "W_KG": {"choice": True, "defaultValue": "KG", "name": "WEIGHT_KG"},
        },
        "dataNeeded": {
            "CONTEXT": {
                "CONTAINER_NUMBER": {"TYPE": "STRING"},
                "DATE_AT_ORIGIN": {"TYPE": "DATE"},
                "ORIGIN_LOCATION": {"TYPE": "STRING"},
            },
            "INPUTS": {
                "FCD_CONTAINER_INFORMATION": {
                    "CATEGORY": "ACTION_CONTEXT_VIEW",
                    "CONTAINER_NUMBER": {"IS_TAGGABLE": False, "TYPE": "STRING"},
                    "SUPPLIER_CODE": {"IS_TAGGABLE": False, "TYPE": "STRING"},
                    "TOTAL_CONTAINER_VALUE": {"IS_TAGGABLE": False, "TYPE": "AMOUNT"},
                    "TOTAL_QUANTITY_IN_UNITS": {"IS_TAGGABLE": False, "TYPE": "NUMBER"},
                    "TYPE": "OBJECT",
                    "VESSEL_NUMBER": {"IS_TAGGABLE": False, "TYPE": "STRING"},
                },
                "FCD_CONTAINER_PRODUCTS_LIST": {
                    "CATEGORY": "ACTION_CONTEXT_VIEW",
                    "CONTAINER_NUMBER": {"IS_TAGGABLE": False, "TYPE": "STRING"},
                    "ITEM_CODE": {"IS_TAGGABLE": True, "TYPE": "STRING"},
                    "ORDER_VALUE": {"IS_TAGGABLE": False, "TYPE": "NUMBER"},
                    "PURCHASE_ORDER_NUMBER": {"IS_TAGGABLE": False, "TYPE": "STRING"},
                    "QUANTITY_IN_PALLETS": {"IS_TAGGABLE": False, "TYPE": "NUMBER"},
                    "QUANTITY_IN_UNITS": {"IS_TAGGABLE": False, "TYPE": "NUMBER"},
                    "SUPPLIER_CODE": {"IS_TAGGABLE": False, "TYPE": "STRING"},
                    "TYPE": "ARRAY",
                },
                "FCD_DEPLOYMENT_ROUTES": {
                    "CATEGORY": "ACTION_CONTEXT_VIEW",
                    "CO2_EMISSION_PER_KG_SHIPPED": {"IS_TAGGABLE": False, "TYPE": "NUMBER_CO2_PER_KG"},
                    "COST_PER_UNIT_CURRENCY": {"IS_TAGGABLE": False, "TYPE": "AMOUNT"},
                    "DESTINATION_LOCATION_CODE": {"IS_TAGGABLE": True, "TYPE": "STRING"},
                    "DISTANCE_KM": {"IS_TAGGABLE": False, "TYPE": "NUMBER_D_KM"},
                    "LEAD_TIME_DAYS": {"IS_TAGGABLE": False, "TYPE": "NUMBER_T_DAYS"},
                    "ORIGIN_LOCATION_CODE": {"IS_TAGGABLE": True, "TYPE": "STRING"},
                    "ROUTE_CODE": {"IS_TAGGABLE": True, "TYPE": "STRING"},
                    "ROUTE_DESCRIPTION": {"IS_TAGGABLE": True, "TYPE": "STRING"},
                    "SUPPLIER_CODE": {"IS_TAGGABLE": False, "TYPE": "STRING"},
                    "TRANSPORTATION_MODE": {"IS_TAGGABLE": True, "TYPE": "STRING"},
                    "TYPE": "OBJECT",
                },
                "FG_CURRENT_AVAILABLE_INVENTORY": {
                    "CATEGORY": "ACTION_CONTEXT_VIEW",
                    "DATE": {"IS_TAGGABLE": False, "TYPE": "DATE"},
                    "FORECAST_DAYS_OF_SUPPLY": {"IS_TAGGABLE": False, "TYPE": "NUMBER_T_DAYS"},
                    "GLOBAL_FORECAST_DOS": {"IS_TAGGABLE": False, "TYPE": "NUMBER_T_DAYS"},
                    "GLOBAL_SALES_DOS": {"IS_TAGGABLE": False, "TYPE": "NUMBER_T_DAYS"},
                    "ITEM_CODE": {"IS_TAGGABLE": True, "TYPE": "STRING"},
                    "LOCATION_CODE": {"IS_TAGGABLE": True, "TYPE": "STRING"},
                    "MONTHLY_FORECASTED_DEMAND": {"IS_TAGGABLE": False, "TYPE": "NUMBER"},
                    "MONTHLY_SALES": {"IS_TAGGABLE": False, "TYPE": "NUMBER"},
                    "ON_HAND_VALUE": {"IS_TAGGABLE": False, "TYPE": "NUMBER"},
                    "QUANTITY_ON_HAND": {"IS_TAGGABLE": False, "TYPE": "NUMBER"},
                    "SALES_DAYS_OF_SUPPLY": {"IS_TAGGABLE": False, "TYPE": "NUMBER_T_DAYS"},
                    "SHORTAGE_VALUE": {"IS_TAGGABLE": False, "TYPE": "NUMBER"},
                    "STANDARD_PRICE_PER_UNIT": {"IS_TAGGABLE": False, "TYPE": "AMOUNT"},
                    "STOCK_TYPE": {"IS_TAGGABLE": False, "TYPE": "STRING"},
                    "SUPPLY": {"IS_TAGGABLE": False, "TYPE": "NUMBER"},
                    "TYPE": "ARRAY",
                },
                "ITEM_MASTER": {
                    "CATEGORY": "MASTER",
                    "ITEM_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "ITEM_DESCRIPTION": {"IS_TAGGABLE": True, "REQUIRED": False, "TYPE": "STRING"},
                    "ITEM_TYPE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "TYPE": "OBJECT",
                    "UNIT_PER_PALLET": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "NUMBER"},
                    "WEIGHT_PER_UNIT_IN_KG": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "NUMBER_W_KG"},
                },
                "LOCATION_ITEM_MASTER": {
                    "CATEGORY": "MASTER",
                    "DAYS_OF_SUPPLY_THRESHOLD": {"IS_TAGGABLE": True, "REQUIRED": False, "TYPE": "NUMBER_T_DAYS"},
                    "ITEM_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "LOCATION_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "STANDARD_COST_PER_UNIT": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "AMOUNT"},
                    "TYPE": "OBJECT",
                },
                "LOCATION_MASTER": {
                    "CATEGORY": "MASTER",
                    "LOCATION_CITY": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "LOCATION_CONTACT_NAME": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "LOCATION_COUNTRY": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "LOCATION_DESCRIPTION": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "LOCATION_ID": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "LOCATION_PRIMARY_LANGUAGE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "LOCATION_TYPE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "LOCATION_ZIP_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "TYPE": "OBJECT",
                },
            },
            "OUTPUTS": {
                "FULL_CONTAINER_DEPLOYMENT_ACTION_DETAILS": {},
                "FULL_CONTAINER_DEPLOYMENT_IMPACT": {},
                "FULL_CONTAINER_DEPLOYMENT_NEW_AVAILABLE_INVENTORY": {},
                "FULL_CONTAINER_DEPLOYMENT_OTHER_INVENTORIES_LIST": {},
                "FULL_CONTAINER_DEPLOYMENT_TRANSFER_ORDER": {},
            },
        },
        "kpis": [
            "COST",
            "FLEXIBILITY",
            "INVENTORY_COVERAGE",
            "INVENTORY_VALUE",
            "RELIABILITY",
            "RESPONSIVENESS",
            "SUSTAINABILITY",
        ],
        "name": "FULL_CONTAINER_DEPLOYMENT",
        "reasons": [
            "f218957f-65a1-49c5-954a-4b1028c495ab",
            "cf92d4d1-2353-42d4-b9ac-bac63eef2fbd",
            "ce47d645-4b00-4cf7-a218-e5855daf5d67",
            "a1dee19b-4544-4e18-8503-74d41553cf19",
            "83b0f297-2c44-4bd1-a2cf-2a051fe53fc7",
            "fac09ace-1d08-48e8-b389-764f41d58a8b",
            "049830a7-9e47-4431-9f44-5a78ea7059bd",
            "74972e98-f150-48a1-9f9a-030ca5d192d8",
        ],
    },
    {
        "actionSettings": {
            "CO2_PER_KG": {"choice": True, "defaultValue": "CO2_KG", "name": "CO2_PER_KG"},
            "DOS_MIN_THRESHOLD": {
                "choice": False,
                "defaultValue": 20,
                "name": "SR_DAYS_OF_SUPPLY_THRESHOLD",
                "required": True,
                "type": "NUMBER",
            },
            "D_KM": {"choice": True, "defaultValue": "KM", "name": "DISTANCE_KM"},
            "SR_RS": {"choice": True, "defaultValue": "SR_ALGO_DISTANCE", "name": "SR_ROUTE_SORTING"},
            "T_DAYS": {"choice": True, "defaultValue": "DAYS", "name": "TIME_DAYS"},
            "V_CO2": {"choice": True, "defaultValue": "M_SQUARE_PER_M_CUBE", "name": "VOLUME_CO2"},
            "W_KG": {"choice": True, "defaultValue": "KG", "name": "WEIGHT_KG"},
        },
        "dataNeeded": {
            "CONTEXT": {
                "ITEM_CODE": {"TYPE": "STRING"},
                "LOCATION_CODE": {"TYPE": "STRING"},
                "QUANTITY_AT_RISK": {"TYPE": "NUMBER"},
            },
            "INPUTS": {
                "ITEM_MASTER": {
                    "CATEGORY": "MASTER",
                    "ITEM_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "ITEM_DESCRIPTION": {"IS_TAGGABLE": True, "REQUIRED": False, "TYPE": "STRING"},
                    "ITEM_TYPE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "TYPE": "OBJECT",
                    "UNIT_PER_PALLET": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "NUMBER"},
                    "WEIGHT_PER_UNIT_IN_KG": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "NUMBER_W_KG"},
                },
                "LOCATION_ITEM_MASTER": {
                    "CATEGORY": "MASTER",
                    "DAYS_OF_SUPPLY_THRESHOLD": {"IS_TAGGABLE": True, "REQUIRED": False, "TYPE": "NUMBER_T_DAYS"},
                    "ITEM_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "LOCATION_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "STANDARD_COST_PER_UNIT": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "AMOUNT"},
                    "TYPE": "OBJECT",
                },
                "LOCATION_MASTERS": {
                    "CATEGORY": "MASTER",
                    "LOCATION_CITY": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "LOCATION_CONTACT_NAME": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "LOCATION_COUNTRY": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "LOCATION_DESCRIPTION": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "LOCATION_ID": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "LOCATION_PRIMARY_LANGUAGE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "LOCATION_TYPE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "LOCATION_ZIP_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "TYPE": "ARRAY",
                },
                "PROCUREMENT_INTERNAL_ROUTES": {
                    "CATEGORY": "ACTION_CONTEXT_VIEW",
                    "CO2_EMISSION_PER_KG_SHIPPED": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "NUMBER_CO2_PER_KG"},
                    "COST_PER_UNIT_CURRENCY": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "AMOUNT"},
                    "DISTANCE_KM": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "NUMBER_D_KM"},
                    "LEAD_TIME_DAYS": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "NUMBER_T_DAYS"},
                    "MODE_OF_TRANSPORTATION": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "OTIF_PERCENT": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "NUMBER"},
                    "RECEIVING_LOCATION": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "ROUTE_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "ROUTE_DESCRIPTION": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "SHIPPING_LOCATION_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "TYPE": "OBJECT",
                },
                "RPM_INVENTORY": {
                    "CATEGORY": "ACTION_CONTEXT_VIEW",
                    "DATE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "DATE"},
                    "DAYS_OF_SUPPLY": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "NUMBER_T_DAYS"},
                    "DEMAND": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "AMOUNT"},
                    "ITEM_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "LOCATION_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "ON_HAND_VALUE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "NUMBER"},
                    "QUANTITY_ON_HAND": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "NUMBER"},
                    "STANDARD_PRICE_PER_UNIT": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "AMOUNT"},
                    "STOCK_TYPE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "SUPPLY": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "NUMBER"},
                    "TYPE": "ARRAY",
                },
            },
            "OUTPUTS": {
                "STOCK_REBALANCING_ACTION_DETAILS": {
                    "CATEGORY": "ACTION_DETAILS",
                    "DELIVERY_DATE": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "DATE"},
                    "FREIGHT_CO2_EMISSION": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "NUMBER_V_CO2"},
                    "FREIGHT_COST": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "AMOUNT"},
                    "RECEIVING_LOCATION_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "SHIPPING_LOCATION_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "TRANSFER_QUANTITY": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "NUMBER"},
                    "TRANSPORTATION_MODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "TYPE": "OBJECT",
                },
                "STOCK_REBALANCING_IMPACT": {
                    "ACTION_DUE_DATE": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "DATE"},
                    "CATEGORY": "RISK_IMPACTS",
                    "DELIVERY_DATE": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "DATE"},
                    "FREIGHT_CO2_EMISSION": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "NUMBER_V_CO2"},
                    "FREIGHT_COST": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "AMOUNT"},
                    "REMAINING_QUANTITY": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "NUMBER"},
                    "TRANSFER_QUANTITY": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "NUMBER"},
                    "TYPE": "OBJECT",
                },
                "STOCK_REBALANCING_NEW_INVENTORY_PLAN": {
                    "CATEGORY": "ACTION_CONTEXT_VIEW",
                    "DATE": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "DATE"},
                    "DAYS_OF_SUPPLY": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "NUMBER_T_DAYS"},
                    "ITEM_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "LOCATION_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "ON_HAND_VALUE": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "NUMBER"},
                    "QUANTITY_ON_HAND": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "NUMBER"},
                    "TYPE": "ARRAY",
                },
                "STOCK_REBALANCING_TRANSFER_ORDER": {
                    "CATEGORY": "RISK_IMPACTS",
                    "DELIVERY_DATE": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "DATE"},
                    "ITEM": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "QUANTITY": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "NUMBER"},
                    "RECEIVING_LOCATION": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "SHIPPING_LOCATION": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "SHIP_DATE": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "DATE"},
                    "TYPE": "OBJECT",
                },
            },
        },
        "kpis": [
            "COST",
            "FLEXIBILITY",
            "INVENTORY_COVERAGE",
            "INVENTORY_VALUE",
            "RELIABILITY",
            "RESPONSIVENESS",
            "SUSTAINABILITY",
        ],
        "name": "STOCK_REBALANCING",
        "reasons": [
            "f218957f-65a1-49c5-954a-4b1028c495ab",
            "3753202b-db06-464f-83da-85b532efd2fa",
            "83b0f297-2c44-4bd1-a2cf-2a051fe53fc7",
            "ac24e537-c528-4cbd-941f-c8a8bf7a4aaa",
            "74972e98-f150-48a1-9f9a-030ca5d192d8",
        ],
    },
    {
        "actionSettings": {
            "CO2_PER_KG": {"choice": True, "defaultValue": "CO2_KG", "name": "CO2_PER_KG"},
            "D_KM": {"choice": True, "defaultValue": "KM", "name": "DISTANCE_KM"},
            "FTL_BTD": {"choice": False, "defaultValue": 1, "name": "FTL_BUFFER_TIME_IN_DAYS", "type": "NUMBER"},
            "FTL_CLT": {"choice": False, "defaultValue": "CONSOLIDATION_HUB", "name": "FTL_CONSOLIDATION_LOCATION_TYPE"},
            "FTL_DT": {"choice": True, "defaultValue": "FTL_ALGO_FORECAST", "name": "FTL_DEMAND_TYPE"},
            "FTL_EP": {"choice": False, "defaultValue": 78, "name": "FTL_EXPIRY_PERIOD", "type": "NUMBER"},
            "FTL_EXDOS": {"choice": False, "defaultValue": 4, "name": "FTL_EXCESS_DOS", "type": "NUMBER"},
            "FTL_FCU": {"choice": True, "defaultValue": "FTL_ALGO_UNIT", "name": "FTL_FREIGHT_COST_UNIT"},
            "FTL_GS_MIN_Q": {"choice": False, "defaultValue": 1000, "name": "FTL_GLOBAL_SHORTAGE_MINIMUM_QUANTITY", "type": "NUMBER"},
            "FTL_MAX_CAPACITY": {"choice": False, "defaultValue": 32, "name": "FTL_MAXIMUM_CAPACITY", "type": "NUMBER"},
            "FTL_MIN_DOS": {"choice": False, "defaultValue": 5, "name": "FTL_MINIMUM_DOS", "type": "NUMBER"},
            "FTL_MIN_LOAD": {"choice": False, "defaultValue": 5, "name": "FTL_MINIMUM_LOAD", "type": "NUMBER"},
            "FTL_RPC": {"choice": True, "defaultValue": "FTL_ALGO_DOS", "name": "FTL_REBALANCING_PRIORITISATION_CRITERIA"},
            "FTL_SHDOS": {"choice": False, "defaultValue": 10, "name": "FTL_SHORTAGE_DOS", "type": "NUMBER"},
            "FTL_SM": {"choice": True, "defaultValue": "FTL_ALGO_QUANTITY", "name": "FTL_TRUCK_LOAD_SORTING_MEASURE"},
            "FTL_SP": {"choice": True, "defaultValue": "FTL_ALGO_LOWEST", "name": "FTL_SORTING_PRIORITISATION"},
            "T_DAYS": {"choice": True, "defaultValue": "DAYS", "name": "TIME_DAYS"},
            "V_CO2": {"choice": True, "defaultValue": "M_SQUARE_PER_M_CUBE", "name": "VOLUME_CO2"},
            "W_KG": {"choice": True, "defaultValue": "KG", "name": "WEIGHT_KG"},
        },
        "dataNeeded": {
            "CONTEXT": {
                "RECEIVING_LOCATION": {"TYPE": "STRING"},
                "SHIPPING_LOCATION": {"TYPE": "STRING"},
                "SHIP_DATE": {"TYPE": "DATE"},
            },
            "INPUTS": {
                "FG_CURRENT_AVAILABLE_INVENTORY": {
                    "CATEGORY": "ACTION_CONTEXT_VIEW",
                    "DATE": {"IS_TAGGABLE": False, "TYPE": "DATE"},
                    "FORECAST_DAYS_OF_SUPPLY": {"IS_TAGGABLE": False, "TYPE": "NUMBER_T_DAYS"},
                    "GLOBAL_FORECAST_DOS": {"IS_TAGGABLE": False, "TYPE": "NUMBER_T_DAYS"},
                    "GLOBAL_SALES_DOS": {"IS_TAGGABLE": False, "TYPE": "NUMBER_T_DAYS"},
                    "ITEM_CODE": {"IS_TAGGABLE": True, "TYPE": "STRING"},
                    "LOCATION_CODE": {"IS_TAGGABLE": True, "TYPE": "STRING"},
                    "MONTHLY_FORECASTED_DEMAND": {"IS_TAGGABLE": False, "TYPE": "NUMBER"},
                    "MONTHLY_SALES": {"IS_TAGGABLE": False, "TYPE": "NUMBER"},
                    "ON_HAND_VALUE": {"IS_TAGGABLE": False, "TYPE": "NUMBER"},
                    "QUANTITY_ON_HAND": {"IS_TAGGABLE": False, "TYPE": "NUMBER"},
                    "SALES_DAYS_OF_SUPPLY": {"IS_TAGGABLE": False, "TYPE": "NUMBER_T_DAYS"},
                    "SHORTAGE_VALUE": {"IS_TAGGABLE": False, "TYPE": "NUMBER"},
                    "STANDARD_PRICE_PER_UNIT": {"IS_TAGGABLE": False, "TYPE": "AMOUNT"},
                    "STOCK_TYPE": {"IS_TAGGABLE": False, "TYPE": "STRING"},
                    "SUPPLY": {"IS_TAGGABLE": False, "TYPE": "NUMBER"},
                    "TYPE": "ARRAY",
                },
                "FG_EXPIRABLE_INVENTORY": {
                    "BATCH_CODE": {"IS_TAGGABLE": False, "TYPE": "STRING"},
                    "CATEGORY": "ACTION_CONTEXT_VIEW",
                    "EXPIRATION_DATE": {"IS_TAGGABLE": False, "TYPE": "DATE"},
                    "ITEM_CODE": {"IS_TAGGABLE": True, "TYPE": "STRING"},
                    "LOCATION_CODE": {"IS_TAGGABLE": True, "TYPE": "STRING"},
                    "QUANTITY_ON_HAND": {"IS_TAGGABLE": False, "TYPE": "NUMBER"},
                    "STOCK_TYPE": {"IS_TAGGABLE": False, "TYPE": "STRING"},
                    "STORAGE_LOCATION": {"IS_TAGGABLE": False, "TYPE": "STRING"},
                    "TYPE": "ARRAY",
                },
                "FTL_INTERNAL_ROUTES": {
                    "CATEGORY": "ACTION_CONTEXT_VIEW",
                    "CO2_EMISSION_PER_KG_SHIPPED": {"IS_TAGGABLE": False, "TYPE": "NUMBER_CO2_PER_KG"},
                    "COST_PER_UNIT_CURRENCY": {"IS_TAGGABLE": False, "TYPE": "AMOUNT"},
                    "DISTANCE_KM": {"IS_TAGGABLE": False, "TYPE": "NUMBER_D_KM"},
                    "LEAD_TIME_DAYS": {"IS_TAGGABLE": False, "TYPE": "NUMBER_T_DAYS"},
                    "RECEIVING_LOCATION_CODE": {"IS_TAGGABLE": True, "TYPE": "STRING"},
                    "ROUTE_CODE": {"IS_TAGGABLE": True, "TYPE": "STRING"},
                    "ROUTE_DESCRIPTION": {"IS_TAGGABLE": True, "TYPE": "STRING"},
                    "SHIPPING_LOCATION_CODE": {"IS_TAGGABLE": True, "TYPE": "STRING"},
                    "TRANSPORTATION_MODE": {"IS_TAGGABLE": True, "TYPE": "STRING"},
                    "TYPE": "ARRAY",
                },
                "ITEM_MASTER": {
                    "CATEGORY": "MASTER",
                    "ITEM_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "ITEM_DESCRIPTION": {"IS_TAGGABLE": True, "REQUIRED": False, "TYPE": "STRING"},
                    "ITEM_TYPE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "TYPE": "OBJECT",
                    "UNIT_PER_PALLET": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "NUMBER"},
                    "WEIGHT_PER_UNIT_IN_KG": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "NUMBER_W_KG"},
                },
                "LOCATION_ITEM_MASTER": {
                    "CATEGORY": "MASTER",
                    "DAYS_OF_SUPPLY_THRESHOLD": {"IS_TAGGABLE": True, "REQUIRED": False, "TYPE": "NUMBER_T_DAYS"},
                    "ITEM_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "LOCATION_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "STANDARD_COST_PER_UNIT": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "AMOUNT"},
                    "TYPE": "OBJECT",
                },
                "LOCATION_MASTER": {
                    "CATEGORY": "MASTER",
                    "LOCATION_CITY": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "LOCATION_CONTACT_NAME": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "LOCATION_COUNTRY": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "LOCATION_DESCRIPTION": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "LOCATION_ID": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "LOCATION_PRIMARY_LANGUAGE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "LOCATION_TYPE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "LOCATION_ZIP_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "TYPE": "OBJECT",
                },
            },
            "OUTPUTS": {
                "ACTION_DETAILS": {},
                "IMPACT": {},
                "TRANSFER_ORDER": {},
                "TRANSFER_PRODUCTS_LIST": {},
                "TRUCK_PRODUCT_LOAD_LIST": {},
            },
        },
        "kpis": [
            "COST",
            "FLEXIBILITY",
            "INVENTORY_COVERAGE",
            "INVENTORY_VALUE",
            "RELIABILITY",
            "RESPONSIVENESS",
            "SUSTAINABILITY",
        ],
        "name": "FULL_TRUCK_LOAD",
        "reasons": [
            "f218957f-65a1-49c5-954a-4b1028c495ab",
            "3753202b-db06-464f-83da-85b532efd2fa",
            "ce47d645-4b00-4cf7-a218-e5855daf5d67",
            "36344863-1904-4c34-a181-ace8f0865c22",
            "7a1c7c14-9532-44b7-be1d-22c96acab584",
            "42f6416c-16c6-475a-9c3d-6d8e194c91e5",
            "74972e98-f150-48a1-9f9a-030ca5d192d8",
        ],
    },
    {
        "actionSettings": {
            "T_DAYS": {"choice": True, "defaultValue": "DAYS", "name": "TIME_DAYS"},
            "V_CO2": {"choice": True, "defaultValue": "M_SQUARE_PER_M_CUBE", "name": "VOLUME_CO2"},
            "W_KG": {"choice": True, "defaultValue": "KG", "name": "WEIGHT_KG"},
        },
        "dataNeeded": {
            "CONTEXT": {
                "ITEM_CODE": {"TYPE": "STRING"},
                "LOCATION_CODE": {"TYPE": "STRING"},
                "QUANTITY_AT_RISK": {"TYPE": "NUMBER"},
            },
            "INPUTS": {
                "ITEM_MASTER": {
                    "CATEGORY": "MASTER",
                    "ITEM_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "ITEM_DESCRIPTION": {"IS_TAGGABLE": True, "REQUIRED": False, "TYPE": "STRING"},
                    "ITEM_TYPE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "TYPE": "OBJECT",
                    "UNIT_PER_PALLET": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "NUMBER"},
                    "WEIGHT_PER_UNIT_IN_KG": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "NUMBER_W_KG"},
                },
                "LOCATION_MASTER": {
                    "CATEGORY": "MASTER",
                    "LOCATION_CITY": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "LOCATION_CONTACT_NAME": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "LOCATION_COUNTRY": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "LOCATION_DESCRIPTION": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "LOCATION_ID": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "LOCATION_PRIMARY_LANGUAGE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "LOCATION_TYPE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "LOCATION_ZIP_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "TYPE": "OBJECT",
                },
                "PROCUREMENT_PO_CONDITION": {
                    "CATEGORY": "ACTION_CONTEXT_VIEW",
                    "CO2_EMISSION": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "NUMBER_V_CO2"},
                    "CONDITION_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "CONDITION_DESCRIPTION": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "COST_PER_UNIT_CURRENCY": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "AMOUNT"},
                    "LEAD_TIME_DAYS": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "NUMBER_T_DAYS"},
                    "MODE_OF_TRANSPORTATION": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "RECEIVING_LOCATION_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "SUPPLIER_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "TYPE": "OBJECT",
                },
                "PROCUREMENT_PURCHASE_ORDER": {
                    "CATEGORY": "ACTION_CONTEXT_VIEW",
                    "CREATION_DATE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "DATE"},
                    "DELIVERY_DATE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "DATE"},
                    "ITEM_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "LINE_NUMBER": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "LINE_VALUE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "NUMBER": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "PURCHASE_COST_PER_UNIT": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "AMOUNT"},
                    "QUANTITY": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "NUMBER"},
                    "RECEIVING_LOCATION_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "SHIPPING_DATE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "DATE"},
                    "STANDARD_INBOUND_ROUTE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "STATUS": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "SUPPLIER_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "TYPE": "OBJECT",
                    "UNIT_OF_MEASURE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                },
                "PROCUREMENT_SHIPPING_CONDITIONS": {
                    "CATEGORY": "ACTION_CONTEXT_VIEW",
                    "CO2_EMISSION": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "NUMBER_V_CO2"},
                    "CONDITION_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "CONDITION_DESCRIPTION": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "COST_PER_UNIT_CURRENCY": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "AMOUNT"},
                    "LEAD_TIME_DAYS": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "NUMBER_T_DAYS"},
                    "MODE_OF_TRANSPORTATION": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "OTIF_PERCENT": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "NUMBER"},
                    "RECEIVING_LOCATION_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "SUPPLIER_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "TYPE": "OBJECT",
                },
                "PROCUREMENT_SUBSTITUTION": {
                    "ALTERNATE_COST_PER_UNIT": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "AMOUNT"},
                    "ALTERNATE_SUPPLIER_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "ALTERNATE_SUPPLIER_COUNTRY_OF_ORIGIN": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "CATEGORY": "ACTION_CONTEXT_VIEW",
                    "ITEM_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "LOCATION_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "SUBSTITUTE_ITEM_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "SUBSTITUTION_QUANTITY_RATIO": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "NUMBER"},
                    "SUPPLIER_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "TYPE": "ARRAY",
                    "UNIT_OF_MEASURE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                },
                "SUPPLIER_MASTER": {
                    "CATEGORY": "MASTER",
                    "LOCATION_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "SUPPLIER_CITY": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "SUPPLIER_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "SUPPLIER_CONTACT_NAME": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "SUPPLIER_COUNTRY": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "SUPPLIER_DESCRIPTION": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "SUPPLIER_ZIP_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "TYPE": "OBJECT",
                },
            },
            "OUTPUTS": {
                "ALTERNATE_SUPPLIER_ACTION_DETAILS": {
                    "ALTERNATE_SUPPLIER_CITY": {"IS_TAGGABLE": True, "REQUIRED": False, "TYPE": "STRING"},
                    "ALTERNATE_SUPPLIER_COST_PER_UNIT": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "AMOUNT"},
                    "ALTERNATE_SUPPLIER_DELIVERY_QUANTITY": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "NUMBER"},
                    "ALTERNATE_SUPPLIER_DESCRIPTION": {"IS_TAGGABLE": False, "REQUIRED": False, "TYPE": "STRING"},
                    "ALTERNAT_SUPPLIER_CODE": {"IS_TAGGABLE": True, "TYPE": "STRING"},
                    "CATEGORY": "ACTION_DETAILS",
                    "DELIVERY_DATE": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "DATE"},
                    "FREIGHT_CO2_EMISSION": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "NUMBER_V_CO2"},
                    "FREIGHT_CO2_EMISSION_IMPACT": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "NUMBER_V_CO2"},
                    "FREIGHT_COST": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "AMOUNT"},
                    "FREIGHT_COST_IMPACT": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "AMOUNT"},
                    "PURCHASE_COST": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "AMOUNT"},
                    "PURCHASE_COST_IMPACT": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "AMOUNT"},
                    "PURCHASE_ORDER_LINE_NUMBER": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "PURCHASE_ORDER_NUMBER": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "TYPE": "OBJECT",
                },
                "ALTERNATE_SUPPLIER_IMPACT": {
                    "ACTION_DUE_DATE": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "DATE"},
                    "CATEGORY": "RISK_IMPACTS",
                    "DELIVERY_DATE": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "DATE"},
                    "DELIVERY_QUANTITY": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "NUMBER"},
                    "FREIGHT_CO2_EMISSION": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "NUMBER_V_CO2"},
                    "FREIGHT_CO2_EMISSION_IMPACT": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "NUMBER_V_CO2"},
                    "FREIGHT_COST": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "AMOUNT"},
                    "FREIGHT_COST_IMPACT": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "AMOUNT"},
                    "PURCHASE_COST": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "AMOUNT"},
                    "PURCHASE_COST_IMPACT": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "AMOUNT"},
                    "REMAINING_QUANTITY": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "NUMBER"},
                    "SHIPPING_DATE": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "DATE"},
                    "TYPE": "OBJECT",
                },
                "ALTERNATE_SUPPLIER_NEW_PURCHASE_ORDER": {
                    "ALTERNATE_COST_PER_UNIT": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "AMOUNT"},
                    "ALTERNATE_SUPPLIER_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "CATEGORY": "RISK_IMPACTS",
                    "DELIVERY_DATE": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "DATE"},
                    "ITEM_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "LINE_VALUE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "MODE_OF_TRANSPORTATION": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "QUANTITY": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "NUMBER"},
                    "RECEIVING_LOCATION_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "SHIPPING_DATE": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "DATE"},
                    "SUPPLIER_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "TYPE": "OBJECT",
                },
                "ALTERNATE_SUPPLIER_UPDATED_PURCHASE_ORDER": {
                    "CATEGORY": "ACTION_CONTEXT_VIEW",
                    "DELIVERY_DATE": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "DATE"},
                    "LINE_NUMBER": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "PURCHASE_ORDER_NUMBER": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "QUANTITY": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "NUMBER"},
                    "SHIPPING_DATE": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "DATE"},
                    "SUPPLIER_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "TYPE": "OBJECT",
                },
            },
        },
        "kpis": [
            "COST",
            "FLEXIBILITY",
            "INVENTORY_COVERAGE",
            "INVENTORY_VALUE",
            "RELIABILITY",
            "RESPONSIVENESS",
            "SUSTAINABILITY",
        ],
        "name": "ALTERNATE_SUPPLIER",
        "reasons": [
            "f845a1fb-95cb-4bd3-b650-4e0684d9c2e7",
            "3ccf43d9-1a7e-482e-89a6-adc6fe175429",
            "125851ba-e49a-433e-a210-3d9477bdbcea",
            "8c7f153f-70a8-458a-9cb4-8b0dc39701b6",
            "c52bb0a0-e647-4b26-8038-49b46a9f5c41",
            "74972e98-f150-48a1-9f9a-030ca5d192d8",
        ],
    },
    {
        "actionSettings": {
            "PD_TR_MODE_AIR": {"choice": False, "defaultValue": "AIR", "name": "MODE_OF_TRANSPORTATION_AIR", "required": True},
            "PD_TR_MODE_EXPRESS": {"choice": False, "defaultValue": "EXPRESS", "name": "MODE_OF_TRANSPORTATION_EXPRESS", "required": True},
            "T_DAYS": {"choice": True, "defaultValue": "DAYS", "name": "TIME_DAYS"},
            "V_CO2": {"choice": True, "defaultValue": "M_SQUARE_PER_M_CUBE", "name": "VOLUME_CO2"},
            "W_KG": {"choice": True, "defaultValue": "KG", "name": "WEIGHT_KG"},
        },
        "dataNeeded": {
            "CONTEXT": {
                "ITEM_CODE": {"TYPE": "STRING"},
                "LOCATION_CODE": {"TYPE": "STRING"},
                "QUANTITY_AT_RISK": {"TYPE": "NUMBER"},
            },
            "INPUTS": {
                "ITEM_MASTER": {
                    "CATEGORY": "MASTER",
                    "ITEM_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "ITEM_DESCRIPTION": {"IS_TAGGABLE": True, "REQUIRED": False, "TYPE": "STRING"},
                    "ITEM_TYPE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "TYPE": "OBJECT",
                    "UNIT_PER_PALLET": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "NUMBER"},
                    "WEIGHT_PER_UNIT_IN_KG": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "NUMBER_W_KG"},
                },
                "LOCATION_MASTER": {
                    "CATEGORY": "MASTER",
                    "LOCATION_CITY": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "LOCATION_CONTACT_NAME": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "LOCATION_COUNTRY": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "LOCATION_DESCRIPTION": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "LOCATION_ID": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "LOCATION_PRIMARY_LANGUAGE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "LOCATION_TYPE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "LOCATION_ZIP_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "TYPE": "OBJECT",
                },
                "PROCUREMENT_PURCHASE_ORDER": {
                    "CATEGORY": "ACTION_CONTEXT_VIEW",
                    "CREATION_DATE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "DATE"},
                    "DELIVERY_DATE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "DATE"},
                    "ITEM_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "LINE_NUMBER": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "LINE_VALUE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "NUMBER": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "PURCHASE_COST_PER_UNIT": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "AMOUNT"},
                    "QUANTITY": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "NUMBER"},
                    "RECEIVING_LOCATION_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "SHIPPING_DATE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "DATE"},
                    "STANDARD_INBOUND_ROUTE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "STATUS": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "SUPPLIER_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "TYPE": "OBJECT",
                    "UNIT_OF_MEASURE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                },
                "PROCUREMENT_SHIPPING_CONDITIONS": {
                    "CATEGORY": "ACTION_CONTEXT_VIEW",
                    "CO2_EMISSION": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "NUMBER_V_CO2"},
                    "CONDITION_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "CONDITION_DESCRIPTION": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "COST_PER_UNIT_CURRENCY": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "AMOUNT"},
                    "LEAD_TIME_DAYS": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "NUMBER_T_DAYS"},
                    "MODE_OF_TRANSPORTATION": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "OTIF_PERCENT": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "NUMBER"},
                    "RECEIVING_LOCATION_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "SUPPLIER_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "TYPE": "OBJECT",
                },
                "RPM_INVENTORY": {
                    "CATEGORY": "ACTION_CONTEXT_VIEW",
                    "DATE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "DATE"},
                    "DAYS_OF_SUPPLY": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "NUMBER_T_DAYS"},
                    "DEMAND": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "AMOUNT"},
                    "ITEM_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "LOCATION_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "ON_HAND_VALUE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "NUMBER"},
                    "QUANTITY_ON_HAND": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "NUMBER"},
                    "STANDARD_PRICE_PER_UNIT": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "AMOUNT"},
                    "STOCK_TYPE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "SUPPLY": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "NUMBER"},
                    "TYPE": "ARRAY",
                },
                "SUPPLIER_MASTER": {
                    "CATEGORY": "MASTER",
                    "LOCATION_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "SUPPLIER_CITY": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "SUPPLIER_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "SUPPLIER_CONTACT_NAME": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "SUPPLIER_COUNTRY": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "SUPPLIER_DESCRIPTION": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "SUPPLIER_ZIP_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "TYPE": "OBJECT",
                },
            },
            "OUTPUTS": {
                "PARTIAL_DELIVERY_ACTION_DETAILS": {
                    "CATEGORY": "ACTION_DETAILS",
                    "DELIVERY_DATE": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "DATE"},
                    "MODE_OF_TRANSPORTATION": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "PARTIAL_DELIVERY_DATE": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "DATE"},
                    "PARTIAL_FREIGHT_CO2_EMISSION": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "NUMBER_V_CO2"},
                    "PARTIAL_FREIGHT_COST": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "NUMBER"},
                    "PURCHASE_ORDER_LINE_NUMBER": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "PURCHASE_ORDER_NUMBER": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "QUANTITY": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "NUMBER"},
                    "REMAINING_QUANTITY": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "NUMBER"},
                    "TYPE": "OBJECT",
                },
                "PARTIAL_DELIVERY_IMPACT": {
                    "ACTION_DUE_DATE": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "DATE"},
                    "CATEGORY": "RISK_IMPACTS",
                    "PARTIAL_DELIVERY_DATE": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "DATE"},
                    "PARTIAL_DELIVERY_PURCHASE_COST": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "NUMBER"},
                    "PARTIAL_DELIVERY_QUANTITY": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "NUMBER"},
                    "PARTIAL_FREIGHT_CO2_EMISSION": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "NUMBER_V_CO2"},
                    "PARTIAL_FREIGHT_COST": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "NUMBER"},
                    "PARTIAL_FREIGHT_COST_IMPACT": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "NUMBER"},
                    "PURCHASE_COST_IMPACT": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "NUMBER"},
                    "REMAINING_DELIVERY_PURCHASE_COST": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "NUMBER"},
                    "REMAINING_QUANTITY": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "NUMBER"},
                    "TYPE": "OBJECT",
                },
                "PARTIAL_DELIVERY_NEW_INVENTORY_PLAN": {
                    "CATEGORY": "ACTION_CONTEXT_VIEW",
                    "DATE": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "DATE"},
                    "DAYS_OF_SUPPLY": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "NUMBER_T_DAYS"},
                    "ITEM_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "ON_HAND_VALUE": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "AMOUNT"},
                    "QUANTITY_ON_HAND": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "NUMBER"},
                    "TYPE": "ARRAY",
                },
                "PARTIAL_DELIVERY_NEW_PURCHASE_ORDER": {
                    "CATEGORY": "RISK_IMPACTS",
                    "ITEM_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "PARTIAL_DELIVERY_DATE": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "DATE"},
                    "PURCHASE_ORDER_COST_PER_UNIT": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "AMOUNT"},
                    "PURCHASE_ORDER_LINE_VALUE": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "STRING"},
                    "PURCHASE_ORDER_NUMBER": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "QUANTITY": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "NUMBER"},
                    "TYPE": "OBJECT",
                },
                "PARTIAL_DELIVERY_UPDATED_PURCHASE_ORDER": {
                    "CATEGORY": "ACTION_CONTEXT_VIEW",
                    "PURCHASE_ORDER_LINE_NUMBER": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "PURCHASE_ORDER_NUMBER": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "QUANTITY": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "NUMBER"},
                    "TYPE": "OBJECT",
                },
            },
        },
        "kpis": [
            "COST",
            "FLEXIBILITY",
            "INVENTORY_COVERAGE",
            "INVENTORY_VALUE",
            "RELIABILITY",
            "RESPONSIVENESS",
            "SUSTAINABILITY",
        ],
        "name": "PARTIAL_DELIVERY",
        "reasons": [
            "12c4c062-b47f-4f14-951e-6a1312648336",
            "ac24e537-c528-4cbd-941f-c8a8bf7a4aaa",
            "d87bfa88-2814-4bcc-a16e-52748a19bc4e",
            "3ccf43d9-1a7e-482e-89a6-adc6fe175429",
            "8c7f153f-70a8-458a-9cb4-8b0dc39701b6",
            "74972e98-f150-48a1-9f9a-030ca5d192d8",
        ],
    },
    {
        "actionSettings": {
            "ED_TR_MODE_AIR": {"choice": False, "defaultValue": "AIR", "name": "MODE_OF_TRANSPORTATION_AIR", "required": True},
            "ED_TR_MODE_EXPRESS": {"choice": False, "defaultValue": "EXPRESS", "name": "MODE_OF_TRANSPORTATION_EXPRESS", "required": True},
            "T_DAYS": {"choice": True, "defaultValue": "DAYS", "name": "TIME_DAYS"},
            "V_CO2": {"choice": True, "defaultValue": "M_SQUARE_PER_M_CUBE", "name": "VOLUME_CO2"},
            "W_KG": {"choice": True, "defaultValue": "KG", "name": "WEIGHT_KG"},
        },
        "dataNeeded": {
            "CONTEXT": {
                "ITEM_CODE": {"TYPE": "STRING"},
                "LOCATION_CODE": {"TYPE": "STRING"},
                "QUANTITY_AT_RISK": {"TYPE": "NUMBER"},
            },
            "INPUTS": {
                "ITEM_MASTER": {
                    "CATEGORY": "MASTER",
                    "ITEM_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "ITEM_DESCRIPTION": {"IS_TAGGABLE": True, "REQUIRED": False, "TYPE": "STRING"},
                    "ITEM_TYPE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "TYPE": "OBJECT",
                    "UNIT_PER_PALLET": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "NUMBER"},
                    "WEIGHT_PER_UNIT_IN_KG": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "NUMBER_W_KG"},
                },
                "LOCATION_MASTER": {
                    "CATEGORY": "MASTER",
                    "LOCATION_CITY": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "LOCATION_CONTACT_NAME": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "LOCATION_COUNTRY": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "LOCATION_DESCRIPTION": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "LOCATION_ID": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "LOCATION_PRIMARY_LANGUAGE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "LOCATION_TYPE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "LOCATION_ZIP_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "TYPE": "OBJECT",
                },
                "PROCUREMENT_PO_CONDITION": {
                    "CATEGORY": "ACTION_CONTEXT_VIEW",
                    "CO2_EMISSION": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "NUMBER_V_CO2"},
                    "CONDITION_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "CONDITION_DESCRIPTION": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "COST_PER_UNIT_CURRENCY": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "AMOUNT"},
                    "LEAD_TIME_DAYS": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "NUMBER_T_DAYS"},
                    "MODE_OF_TRANSPORTATION": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "RECEIVING_LOCATION_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "SUPPLIER_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "TYPE": "OBJECT",
                },
                "PROCUREMENT_PURCHASE_ORDER": {
                    "CATEGORY": "ACTION_CONTEXT_VIEW",
                    "CREATION_DATE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "DATE"},
                    "DELIVERY_DATE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "DATE"},
                    "ITEM_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "LINE_NUMBER": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "LINE_VALUE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "NUMBER": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "PURCHASE_COST_PER_UNIT": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "AMOUNT"},
                    "QUANTITY": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "NUMBER"},
                    "RECEIVING_LOCATION_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "SHIPPING_DATE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "DATE"},
                    "STANDARD_INBOUND_ROUTE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "STATUS": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "SUPPLIER_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "TYPE": "OBJECT",
                    "UNIT_OF_MEASURE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                },
                "PROCUREMENT_SHIPPING_CONDITIONS": {
                    "CATEGORY": "ACTION_CONTEXT_VIEW",
                    "CO2_EMISSION": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "NUMBER_V_CO2"},
                    "CONDITION_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "CONDITION_DESCRIPTION": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "COST_PER_UNIT_CURRENCY": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "AMOUNT"},
                    "LEAD_TIME_DAYS": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "NUMBER_T_DAYS"},
                    "MODE_OF_TRANSPORTATION": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "OTIF_PERCENT": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "NUMBER"},
                    "RECEIVING_LOCATION_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "SUPPLIER_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "TYPE": "OBJECT",
                },
                "SUPPLIER_MASTER": {
                    "CATEGORY": "MASTER",
                    "LOCATION_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "SUPPLIER_CITY": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "SUPPLIER_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "SUPPLIER_CONTACT_NAME": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "SUPPLIER_COUNTRY": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "SUPPLIER_DESCRIPTION": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "SUPPLIER_ZIP_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "TYPE": "OBJECT",
                },
            },
            "OUTPUTS": {
                "EXPRESS_DELIVERY_ACTION_DETAILS": {
                    "CATEGORY": "ACTION_DETAILS",
                    "DELIVERY_DATE": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "DATE"},
                    "FREIGHT_CO2_EMISSION": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "NUMBER_V_CO2"},
                    "FREIGHT_COST": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "AMOUNT"},
                    "MODE_OF_TRANSPORTATION": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "PURCHASE_ORDER_LINE_NUMBER": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "PURCHASE_ORDER_NUMBER": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "QUANTITY": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "NUMBER"},
                    "TYPE": "OBJECT",
                },
                "EXPRESS_DELIVERY_IMPACT": {
                    "ACTION_DUE_DATE": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "DATE"},
                    "CATEGORY": "RISK_IMPACTS",
                    "DELIVERY_DATE": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "DATE"},
                    "DELIVERY_QUANTITY": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "NUMBER"},
                    "FREIGHT_CO2_EMISSION": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "NUMBER_V_CO2"},
                    "FREIGHT_CO2_EMISSION_IMPACT": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "NUMBER_V_CO2"},
                    "FREIGHT_COST": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "AMOUNT"},
                    "FREIGHT_COST_IMPACT": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "AMOUNT"},
                    "REMAINING_QUANTITY": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "NUMBER"},
                    "SHIPPING_DATE": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "DATE"},
                    "TYPE": "OBJECT",
                },
                "EXPRESS_DELIVERY_UPDATED_PURCHASE_ORDER": {
                    "CATEGORY": "RISK_IMPACTS",
                    "DELIVERY_DATE": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "DATE"},
                    "LINE_NUMBER": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "PURCHASE_ORDER_NUMBER": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "QUANTITY": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "NUMBER"},
                    "SHIPPING_DATE": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "DATE"},
                    "TYPE": "OBJECT",
                },
            },
        },
        "kpis": [
            "COST",
            "FLEXIBILITY",
            "INVENTORY_COVERAGE",
            "INVENTORY_VALUE",
            "RELIABILITY",
            "RESPONSIVENESS",
            "SUSTAINABILITY",
        ],
        "name": "EXPRESS_DELIVERY",
        "reasons": [
            "57465c0f-3be8-4f91-b35d-80983bcd2fef",
            "3ccf43d9-1a7e-482e-89a6-adc6fe175429",
            "8eab7fe3-24ff-46ff-a693-fcc5c4bff2a0",
            "8c7f153f-70a8-458a-9cb4-8b0dc39701b6",
            "74972e98-f150-48a1-9f9a-030ca5d192d8",
        ],
    },
    {
        "actionSettings": {
            "SUB_TR_MODE_AIR": {"choice": False, "defaultValue": "AIR", "name": "MODE_OF_TRANSPORTATION_AIR", "required": True},
            "SUB_TR_MODE_EXPRESS": {"choice": False, "defaultValue": "EXPRESS", "name": "MODE_OF_TRANSPORTATION_EXPRESS", "required": True},
            "T_DAYS": {"choice": True, "defaultValue": "DAYS", "name": "TIME_DAYS"},
            "V_CO2": {"choice": True, "defaultValue": "M_SQUARE_PER_M_CUBE", "name": "VOLUME_CO2"},
            "W_KG": {"choice": True, "defaultValue": "KG", "name": "WEIGHT_KG"},
        },
        "dataNeeded": {
            "CONTEXT": {
                "ITEM_CODE": {"TYPE": "STRING"},
                "LOCATION_CODE": {"TYPE": "STRING"},
                "QUANTITY_AT_RISK": {"TYPE": "NUMBER"},
            },
            "INPUTS": {
                "ITEM_MASTER": {
                    "CATEGORY": "MASTER",
                    "ITEM_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "ITEM_DESCRIPTION": {"IS_TAGGABLE": True, "REQUIRED": False, "TYPE": "STRING"},
                    "ITEM_TYPE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "TYPE": "OBJECT",
                    "UNIT_PER_PALLET": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "NUMBER"},
                    "WEIGHT_PER_UNIT_IN_KG": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "NUMBER_W_KG"},
                },
                "LOCATION_MASTER": {
                    "CATEGORY": "MASTER",
                    "LOCATION_CITY": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "LOCATION_CONTACT_NAME": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "LOCATION_COUNTRY": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "LOCATION_DESCRIPTION": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "LOCATION_ID": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "LOCATION_PRIMARY_LANGUAGE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "LOCATION_TYPE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "LOCATION_ZIP_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "TYPE": "OBJECT",
                },
                "PROCUREMENT_PO_CONDITION": {
                    "CATEGORY": "ACTION_CONTEXT_VIEW",
                    "CO2_EMISSION": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "NUMBER_V_CO2"},
                    "CONDITION_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "CONDITION_DESCRIPTION": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "COST_PER_UNIT_CURRENCY": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "AMOUNT"},
                    "LEAD_TIME_DAYS": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "NUMBER_T_DAYS"},
                    "MODE_OF_TRANSPORTATION": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "RECEIVING_LOCATION_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "SUPPLIER_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "TYPE": "OBJECT",
                },
                "PROCUREMENT_PURCHASE_ORDER": {
                    "CATEGORY": "ACTION_CONTEXT_VIEW",
                    "CREATION_DATE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "DATE"},
                    "DELIVERY_DATE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "DATE"},
                    "ITEM_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "LINE_NUMBER": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "LINE_VALUE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "NUMBER": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "PURCHASE_COST_PER_UNIT": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "AMOUNT"},
                    "QUANTITY": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "NUMBER"},
                    "RECEIVING_LOCATION_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "SHIPPING_DATE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "DATE"},
                    "STANDARD_INBOUND_ROUTE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "STATUS": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "SUPPLIER_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "TYPE": "OBJECT",
                    "UNIT_OF_MEASURE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                },
                "PROCUREMENT_SHIPPING_CONDITIONS": {
                    "CATEGORY": "ACTION_CONTEXT_VIEW",
                    "CO2_EMISSION": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "NUMBER_V_CO2"},
                    "CONDITION_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "CONDITION_DESCRIPTION": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "COST_PER_UNIT_CURRENCY": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "AMOUNT"},
                    "LEAD_TIME_DAYS": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "NUMBER_T_DAYS"},
                    "MODE_OF_TRANSPORTATION": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "OTIF_PERCENT": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "NUMBER"},
                    "RECEIVING_LOCATION_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "SUPPLIER_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "TYPE": "OBJECT",
                },
                "PROCUREMENT_SUBSTITUTION": {
                    "ALTERNATE_COST_PER_UNIT": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "AMOUNT"},
                    "ALTERNATE_SUPPLIER_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "ALTERNATE_SUPPLIER_COUNTRY_OF_ORIGIN": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "CATEGORY": "ACTION_CONTEXT_VIEW",
                    "ITEM_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "LOCATION_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "SUBSTITUTE_ITEM_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "SUBSTITUTION_QUANTITY_RATIO": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "NUMBER"},
                    "SUPPLIER_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "TYPE": "ARRAY",
                    "UNIT_OF_MEASURE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                },
                "SUBSTITUTE_ITEM_MASTER": {
                    "CATEGORY": "MASTER",
                    "ITEM_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "ITEM_DESCRIPTION": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "ITEM_TYPE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "TYPE": "OBJECT",
                    "UNIT_PER_PALLET": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "NUMBER"},
                    "WEIGHT_PER_UNIT_IN_KG": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "NUMBER_W_KG"},
                },
            },
            "OUTPUTS": {
                "SUBSTITUTION_ACTION_DETAILS": {
                    "CATEGORY": "ACTION_DETAILS",
                    "DELIVERY_DATE": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "DATE"},
                    "FREIGHT_CO2_EMISSION": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "NUMBER_V_CO2"},
                    "FREIGHT_CO2_EMISSION_IMPACT": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "NUMBER_V_CO2"},
                    "FREIGHT_COST": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "AMOUNT"},
                    "FREIGHT_COST_IMPACT": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "AMOUNT"},
                    "PURCHASE_COST": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "AMOUNT"},
                    "PURCHASE_COST_IMPACT": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "NUMBER"},
                    "SHIP_DATE": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "DATE"},
                    "SUBSTITUTE_COST_PER_UNIT": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "AMOUNT"},
                    "SUBSTITUTE_ITEM_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "SUBSTITUTE_ITEM_RATIO": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "NUMBER"},
                    "SUBSTITUTE_QUANTITY": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "NUMBER"},
                    "TYPE": "OBJECT",
                },
                "SUBSTITUTION_IMPACT": {
                    "ACTION_DUE_DATE": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "DATE"},
                    "CATEGORY": "RISK_IMPACTS",
                    "DELIVERY_DATE": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "DATE"},
                    "FREIGHT_CO2_EMISSION": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "AMOUNT"},
                    "FREIGHT_CO2_EMISSION_IMPACT": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "NUMBER_V_CO2"},
                    "FREIGHT_COST": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "AMOUNT"},
                    "FREIGHT_COST_IMPACT": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "AMOUNT"},
                    "PURCHASE_COST": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "AMOUNT"},
                    "PURCHASE_COST_IMPACT": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "AMOUNT"},
                    "REMAINING_QUANTITY": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "NUMBER"},
                    "SHIPPING_DATE": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "DATE"},
                    "SUBSTITUTE_COST_PER_UNIT": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "NUMBER"},
                    "SUBSTITUTE_ITEM_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "SUBSTITUTION_DELIVERY_QUANTITY": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "NUMBER"},
                    "SUBSTITUTION_QUANTITY_RATIO": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "NUMBER"},
                    "TYPE": "OBJECT",
                },
                "SUBSTITUTION_NEW_PURCHASE_ORDER": {
                    "CATEGORY": "RISK_IMPACTS",
                    "DELIVERY_DATE": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "DATE"},
                    "ITEM_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "PO_LINE_NUMBER": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "PO_NUMBER": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "PURCHASE_COST_PER_UNIT": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "AMOUNT"},
                    "QUANTITY": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "NUMBER"},
                    "SHIP_DATE": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "DATE"},
                    "TYPE": "OBJECT",
                },
                "SUBSTITUTION_UPDATED_PURCHASE_ORDER": {
                    "CATEGORY": "ACTION_CONTEXT_VIEW",
                    "PO_LINE_NUMBER": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "PO_NUMBER": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "QUANTITY": {"IS_TAGGABLE": False, "REQUIRED": True, "TYPE": "NUMBER"},
                    "TYPE": "OBJECT",
                },
            },
        },
        "kpis": [
            "COST",
            "FLEXIBILITY",
            "INVENTORY_COVERAGE",
            "INVENTORY_VALUE",
            "RELIABILITY",
            "RESPONSIVENESS",
            "SUSTAINABILITY",
        ],
        "name": "SUBSTITUTION",
        "reasons": [
            "3ccf43d9-1a7e-482e-89a6-adc6fe175429",
            "8c7f153f-70a8-458a-9cb4-8b0dc39701b6",
            "ae3693fe-6bd7-46b1-86f8-c3b43eeb5039",
            "4e83251e-0185-4ed7-bf98-834d18460836",
            "442e4216-8fc2-46b6-a623-ce6f2cf582cc",
            "c30b176d-5237-451b-a4cf-fda46f71fece",
            "74972e98-f150-48a1-9f9a-030ca5d192d8",
        ],
    },
    {
        "actionSettings": {"V_CO2": {"choice": True, "defaultValue": "M_SQUARE_PER_M_CUBE", "name": "VOLUME_CO2"}},
        "dataNeeded": {
            "CONTEXT": {
                "ITEM_CODE": {"TYPE": "STRING"},
                "LOCATION_CODE": {"TYPE": "STRING"},
                "QUANTITY_AT_RISK": {"TYPE": "STRING"},
            },
            "INPUTS": {
                "ITEM_MASTER": {
                    "CATEGORY": "MASTER",
                    "ITEM_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "ITEM_DESCRIPTION": {"IS_TAGGABLE": True, "REQUIRED": False, "TYPE": "STRING"},
                    "ITEM_TYPE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "TYPE": "OBJECT",
                    "UNIT_PER_PALLET": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "NUMBER"},
                    "WEIGHT_PER_UNIT_IN_KG": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "NUMBER_W_KG"},
                },
                "LOCATION_ITEM_MASTER": {
                    "CATEGORY": "MASTER",
                    "DAYS_OF_SUPPLY_THRESHOLD": {"IS_TAGGABLE": True, "REQUIRED": False, "TYPE": "NUMBER_T_DAYS"},
                    "ITEM_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "LOCATION_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "STANDARD_COST_PER_UNIT": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "AMOUNT"},
                    "TYPE": "OBJECT",
                },
                "LOCATION_MASTERS": {
                    "CATEGORY": "MASTER",
                    "LOCATION_CITY": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "LOCATION_CONTACT_NAME": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "LOCATION_COUNTRY": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "LOCATION_DESCRIPTION": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "LOCATION_ID": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "LOCATION_PRIMARY_LANGUAGE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "LOCATION_TYPE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "LOCATION_ZIP_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "TYPE": "ARRAY",
                },
                "PROCUREMENT_INTERNAL_ROUTES": {
                    "CATEGORY": "ACTION_CONTEXT_VIEW",
                    "CO2_EMISSION_PER_KG_SHIPPED": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "NUMBER_CO2_PER_KG"},
                    "COST_PER_UNIT_CURRENCY": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "AMOUNT"},
                    "DISTANCE_KM": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "NUMBER_D_KM"},
                    "LEAD_TIME_DAYS": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "NUMBER_T_DAYS"},
                    "MODE_OF_TRANSPORTATION": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "OTIF_PERCENT": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "NUMBER"},
                    "RECEIVING_LOCATION": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "ROUTE_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "ROUTE_DESCRIPTION": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "SHIPPING_LOCATION_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "TYPE": "OBJECT",
                },
                "PROCUREMENT_PO_CONDITION": {
                    "CATEGORY": "ACTION_CONTEXT_VIEW",
                    "CO2_EMISSION": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "NUMBER_V_CO2"},
                    "CONDITION_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "CONDITION_DESCRIPTION": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "COST_PER_UNIT_CURRENCY": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "AMOUNT"},
                    "LEAD_TIME_DAYS": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "NUMBER_T_DAYS"},
                    "MODE_OF_TRANSPORTATION": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "RECEIVING_LOCATION_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "SUPPLIER_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "TYPE": "OBJECT",
                },
                "PROCUREMENT_PURCHASE_ORDER": {
                    "CATEGORY": "ACTION_CONTEXT_VIEW",
                    "CREATION_DATE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "DATE"},
                    "DELIVERY_DATE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "DATE"},
                    "ITEM_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "LINE_NUMBER": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "LINE_VALUE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "NUMBER": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "PURCHASE_COST_PER_UNIT": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "AMOUNT"},
                    "QUANTITY": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "NUMBER"},
                    "RECEIVING_LOCATION_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "SHIPPING_DATE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "DATE"},
                    "STANDARD_INBOUND_ROUTE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "STATUS": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "SUPPLIER_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "TYPE": "OBJECT",
                    "UNIT_OF_MEASURE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                },
                "PROCUREMENT_SHIPPING_CONDITIONS": {
                    "CATEGORY": "ACTION_CONTEXT_VIEW",
                    "CO2_EMISSION": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "NUMBER_V_CO2"},
                    "CONDITION_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "CONDITION_DESCRIPTION": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "COST_PER_UNIT_CURRENCY": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "AMOUNT"},
                    "LEAD_TIME_DAYS": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "NUMBER_T_DAYS"},
                    "MODE_OF_TRANSPORTATION": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "OTIF_PERCENT": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "NUMBER"},
                    "RECEIVING_LOCATION_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "SUPPLIER_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "TYPE": "OBJECT",
                },
                "PROCUREMENT_SUBSTITUTION": {
                    "ALTERNATE_COST_PER_UNIT": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "AMOUNT"},
                    "ALTERNATE_SUPPLIER_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "ALTERNATE_SUPPLIER_COUNTRY_OF_ORIGIN": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "CATEGORY": "ACTION_CONTEXT_VIEW",
                    "ITEM_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "LOCATION_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "SUBSTITUTE_ITEM_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "SUBSTITUTION_QUANTITY_RATIO": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "NUMBER"},
                    "SUPPLIER_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "TYPE": "ARRAY",
                    "UNIT_OF_MEASURE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                },
            },
            "OUTPUTS": {
                "AGENT_AI_ACTION_DETAILS": {
                    "ACTION": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "CATEGORY": "ACTION_DETAILS",
                    "EXPLANATION": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "SCORE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "TYPE": "OBJECT",
                },
                "AGENT_AI_IMPACT": {
                    "CATEGORY": "RISK_IMPACTS",
                    "DELIVERY_DATE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "DATE"},
                    "LOCATION_CODE": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "STRING"},
                    "QUANTITY_AT_RISK": {"IS_TAGGABLE": True, "REQUIRED": True, "TYPE": "NUMBER"},
                    "TYPE": "OBJECT",
                },
            },
        },
        "kpis": [
            "FLEXIBILITY",
            "RELIABILITY",
            "RESPONSIVENESS",
        ],
        "name": "AGENT_AI_PROCUREMENT",
        "reasons": [
            "f218957f-65a1-49c5-954a-4b1028c495ab",
            "83b0f297-2c44-4bd1-a2cf-2a051fe53fc7",
            "74972e98-f150-48a1-9f9a-030ca5d192d8",
        ],
    },
]


# fmt: on


class TestActionData:
    @pytest.mark.parametrize("action_data", ACTION_DATA_LIST, ids=lambda x: x["name"])  # type: ignore
    def test_action_data(self, action_data: dict[str, t.Any]) -> None:
        """
        Check that the ActionData schema can be validated and converted to a dictionary.
        This test ensures that the ActionData model can handle the provided action data
        and that the keys are correctly cased as per the original schema.
        """
        # Convert the ACTION_DATA dictionary to an ActionData instance
        action_data_instance = ActionData.model_validate(action_data)

        # Convert the ActionData instance back to a dictionary
        action_data_dict = action_data_instance.model_dump(by_alias=True, exclude_unset=True)

        # Convert reason UUIDs to strings for comparison
        action_data_dict["reasons"] = [str(reason) for reason in action_data_dict["reasons"]]

        # Assert that the converted dictionary matches the original ACTION_DATA
        assert action_data_dict == action_data
