# coding: utf-8

"""
    DSP Backend

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from akridata_dsp.configuration import Configuration


class AnnotationsState(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'state': 'LabelResultState',
        'idxs': 'list[int]'
    }

    attribute_map = {
        'state': 'state',
        'idxs': 'idxs'
    }

    def __init__(self, state=None, idxs=None, local_vars_configuration=None):  # noqa: E501
        """AnnotationsState - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._state = None
        self._idxs = None
        self.discriminator = None

        self.state = state
        if idxs is not None:
            self.idxs = idxs

    @property
    def state(self):
        """Gets the state of this AnnotationsState.  # noqa: E501


        :return: The state of this AnnotationsState.  # noqa: E501
        :rtype: LabelResultState
        """
        return self._state

    @state.setter
    def state(self, state):
        """Sets the state of this AnnotationsState.


        :param state: The state of this AnnotationsState.  # noqa: E501
        :type state: LabelResultState
        """
        if self.local_vars_configuration.client_side_validation and state is None:  # noqa: E501
            raise ValueError("Invalid value for `state`, must not be `None`")  # noqa: E501

        self._state = state

    @property
    def idxs(self):
        """Gets the idxs of this AnnotationsState.  # noqa: E501


        :return: The idxs of this AnnotationsState.  # noqa: E501
        :rtype: list[int]
        """
        return self._idxs

    @idxs.setter
    def idxs(self, idxs):
        """Sets the idxs of this AnnotationsState.


        :param idxs: The idxs of this AnnotationsState.  # noqa: E501
        :type idxs: list[int]
        """

        self._idxs = idxs

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AnnotationsState):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, AnnotationsState):
            return True

        return self.to_dict() != other.to_dict()
