# coding: utf-8

"""
    DSP Backend

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from akridata_dsp.configuration import Configuration


class ResultsetResponseSequenceItem(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'file_id': 'int',
        'frame_idx_in_file': 'int',
        'point_id': 'int',
        'file_path': 'str',
        'url': 'str',
        'similarity': 'float',
        'high_res_url': 'str',
        'key_frames': 'list[SequenceFrameItem]'
    }

    attribute_map = {
        'file_id': 'file_id',
        'frame_idx_in_file': 'frame_idx_in_file',
        'point_id': 'point_id',
        'file_path': 'file_path',
        'url': 'url',
        'similarity': 'similarity',
        'high_res_url': 'high_res_url',
        'key_frames': 'key_frames'
    }

    def __init__(self, file_id=None, frame_idx_in_file=None, point_id=None, file_path=None, url=None, similarity=None, high_res_url=None, key_frames=None, local_vars_configuration=None):  # noqa: E501
        """ResultsetResponseSequenceItem - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._file_id = None
        self._frame_idx_in_file = None
        self._point_id = None
        self._file_path = None
        self._url = None
        self._similarity = None
        self._high_res_url = None
        self._key_frames = None
        self.discriminator = None

        self.file_id = file_id
        if frame_idx_in_file is not None:
            self.frame_idx_in_file = frame_idx_in_file
        if point_id is not None:
            self.point_id = point_id
        if file_path is not None:
            self.file_path = file_path
        if url is not None:
            self.url = url
        if similarity is not None:
            self.similarity = similarity
        if high_res_url is not None:
            self.high_res_url = high_res_url
        if key_frames is not None:
            self.key_frames = key_frames

    @property
    def file_id(self):
        """Gets the file_id of this ResultsetResponseSequenceItem.  # noqa: E501


        :return: The file_id of this ResultsetResponseSequenceItem.  # noqa: E501
        :rtype: int
        """
        return self._file_id

    @file_id.setter
    def file_id(self, file_id):
        """Sets the file_id of this ResultsetResponseSequenceItem.


        :param file_id: The file_id of this ResultsetResponseSequenceItem.  # noqa: E501
        :type file_id: int
        """
        if self.local_vars_configuration.client_side_validation and file_id is None:  # noqa: E501
            raise ValueError("Invalid value for `file_id`, must not be `None`")  # noqa: E501

        self._file_id = file_id

    @property
    def frame_idx_in_file(self):
        """Gets the frame_idx_in_file of this ResultsetResponseSequenceItem.  # noqa: E501


        :return: The frame_idx_in_file of this ResultsetResponseSequenceItem.  # noqa: E501
        :rtype: int
        """
        return self._frame_idx_in_file

    @frame_idx_in_file.setter
    def frame_idx_in_file(self, frame_idx_in_file):
        """Sets the frame_idx_in_file of this ResultsetResponseSequenceItem.


        :param frame_idx_in_file: The frame_idx_in_file of this ResultsetResponseSequenceItem.  # noqa: E501
        :type frame_idx_in_file: int
        """

        self._frame_idx_in_file = frame_idx_in_file

    @property
    def point_id(self):
        """Gets the point_id of this ResultsetResponseSequenceItem.  # noqa: E501


        :return: The point_id of this ResultsetResponseSequenceItem.  # noqa: E501
        :rtype: int
        """
        return self._point_id

    @point_id.setter
    def point_id(self, point_id):
        """Sets the point_id of this ResultsetResponseSequenceItem.


        :param point_id: The point_id of this ResultsetResponseSequenceItem.  # noqa: E501
        :type point_id: int
        """

        self._point_id = point_id

    @property
    def file_path(self):
        """Gets the file_path of this ResultsetResponseSequenceItem.  # noqa: E501


        :return: The file_path of this ResultsetResponseSequenceItem.  # noqa: E501
        :rtype: str
        """
        return self._file_path

    @file_path.setter
    def file_path(self, file_path):
        """Sets the file_path of this ResultsetResponseSequenceItem.


        :param file_path: The file_path of this ResultsetResponseSequenceItem.  # noqa: E501
        :type file_path: str
        """

        self._file_path = file_path

    @property
    def url(self):
        """Gets the url of this ResultsetResponseSequenceItem.  # noqa: E501


        :return: The url of this ResultsetResponseSequenceItem.  # noqa: E501
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this ResultsetResponseSequenceItem.


        :param url: The url of this ResultsetResponseSequenceItem.  # noqa: E501
        :type url: str
        """

        self._url = url

    @property
    def similarity(self):
        """Gets the similarity of this ResultsetResponseSequenceItem.  # noqa: E501


        :return: The similarity of this ResultsetResponseSequenceItem.  # noqa: E501
        :rtype: float
        """
        return self._similarity

    @similarity.setter
    def similarity(self, similarity):
        """Sets the similarity of this ResultsetResponseSequenceItem.


        :param similarity: The similarity of this ResultsetResponseSequenceItem.  # noqa: E501
        :type similarity: float
        """

        self._similarity = similarity

    @property
    def high_res_url(self):
        """Gets the high_res_url of this ResultsetResponseSequenceItem.  # noqa: E501


        :return: The high_res_url of this ResultsetResponseSequenceItem.  # noqa: E501
        :rtype: str
        """
        return self._high_res_url

    @high_res_url.setter
    def high_res_url(self, high_res_url):
        """Sets the high_res_url of this ResultsetResponseSequenceItem.


        :param high_res_url: The high_res_url of this ResultsetResponseSequenceItem.  # noqa: E501
        :type high_res_url: str
        """

        self._high_res_url = high_res_url

    @property
    def key_frames(self):
        """Gets the key_frames of this ResultsetResponseSequenceItem.  # noqa: E501


        :return: The key_frames of this ResultsetResponseSequenceItem.  # noqa: E501
        :rtype: list[SequenceFrameItem]
        """
        return self._key_frames

    @key_frames.setter
    def key_frames(self, key_frames):
        """Sets the key_frames of this ResultsetResponseSequenceItem.


        :param key_frames: The key_frames of this ResultsetResponseSequenceItem.  # noqa: E501
        :type key_frames: list[SequenceFrameItem]
        """

        self._key_frames = key_frames

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ResultsetResponseSequenceItem):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ResultsetResponseSequenceItem):
            return True

        return self.to_dict() != other.to_dict()
