# coding: utf-8

"""
    DSP Backend

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from akridata_dsp.configuration import Configuration


class VideoSnippetGenerateRequest(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'point_id': 'int',
        'request_id': 'str'
    }

    attribute_map = {
        'point_id': 'point_id',
        'request_id': 'request_id'
    }

    def __init__(self, point_id=None, request_id=None, local_vars_configuration=None):  # noqa: E501
        """VideoSnippetGenerateRequest - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._point_id = None
        self._request_id = None
        self.discriminator = None

        self.point_id = point_id
        self.request_id = request_id

    @property
    def point_id(self):
        """Gets the point_id of this VideoSnippetGenerateRequest.  # noqa: E501


        :return: The point_id of this VideoSnippetGenerateRequest.  # noqa: E501
        :rtype: int
        """
        return self._point_id

    @point_id.setter
    def point_id(self, point_id):
        """Sets the point_id of this VideoSnippetGenerateRequest.


        :param point_id: The point_id of this VideoSnippetGenerateRequest.  # noqa: E501
        :type point_id: int
        """
        if self.local_vars_configuration.client_side_validation and point_id is None:  # noqa: E501
            raise ValueError("Invalid value for `point_id`, must not be `None`")  # noqa: E501

        self._point_id = point_id

    @property
    def request_id(self):
        """Gets the request_id of this VideoSnippetGenerateRequest.  # noqa: E501


        :return: The request_id of this VideoSnippetGenerateRequest.  # noqa: E501
        :rtype: str
        """
        return self._request_id

    @request_id.setter
    def request_id(self, request_id):
        """Sets the request_id of this VideoSnippetGenerateRequest.


        :param request_id: The request_id of this VideoSnippetGenerateRequest.  # noqa: E501
        :type request_id: str
        """
        if self.local_vars_configuration.client_side_validation and request_id is None:  # noqa: E501
            raise ValueError("Invalid value for `request_id`, must not be `None`")  # noqa: E501

        self._request_id = request_id

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, VideoSnippetGenerateRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, VideoSnippetGenerateRequest):
            return True

        return self.to_dict() != other.to_dict()
