from .EYPA import GetScreen
from .EYPA import ScreenResizable
from .EYPA import UpdateScreen
from .EYPA import LoopScreen
from .EYPA import AddTextButton
from .EYPA import AddTextLabel
from .EYPA import Config
from .EYPA import GetInfo
from .EYPA import SetScreenSize
from .EYPA import AddShape
from .EYPA import AddCharacter
from .EYPA import Wait
from .EYPA import GetCharacterX
from .EYPA import GetCharacterY