# coding: utf-8

"""
    GroupDocs.Rewriter API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 25.7.0
    Contact: anton.perhunov@aspose.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class DegreeEnum(str, Enum):
    """
    DegreeEnum
    """

    """
    allowed enum values
    """
    OFF = 'Off'
    MEDIUM = 'Medium'
    HIGH = 'High'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of DegreeEnum from a JSON string"""
        return cls(json.loads(json_str))


