
class InsufficientPermissionsError(PermissionError): ...

class InvalidUsernameError(ValueError): ...

class InvalidInputError(ValueError): ...

class NotFoundError(ValueError): ...

class ProcessNotFoundError(NotFoundError): ...

class ContainerNotFoundError(NotFoundError): ...

class DuplicateError(ValueError): ...