# coding: utf-8

"""
    API Docs

    API Documentation to interact with

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from odin_sdk.models.get_chat_analytics_response_metrics import GetChatAnalyticsResponseMetrics

class TestGetChatAnalyticsResponseMetrics(unittest.TestCase):
    """GetChatAnalyticsResponseMetrics unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetChatAnalyticsResponseMetrics:
        """Test GetChatAnalyticsResponseMetrics
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetChatAnalyticsResponseMetrics`
        """
        model = GetChatAnalyticsResponseMetrics()
        if include_optional:
            return GetChatAnalyticsResponseMetrics(
                average_response_time = None,
                average_queries_per_chat = None,
                average_query_token_count = None,
                average_response_token_count = None,
                total_upvotes = None,
                total_downvotes = None,
                total_messages = None,
                average_images_generated = None,
                total_document_usage = None,
                total_kb_search = None,
                total_images_generated = None,
                top_keywords = None,
                top_questions = None,
                regenerated_requests = None,
                users_message_counts = None,
                top_documents = None
            )
        else:
            return GetChatAnalyticsResponseMetrics(
                average_response_time = None,
                average_queries_per_chat = None,
                average_query_token_count = None,
                average_response_token_count = None,
                total_upvotes = None,
                total_downvotes = None,
                total_messages = None,
                average_images_generated = None,
                total_document_usage = None,
                total_kb_search = None,
                total_images_generated = None,
                top_keywords = None,
                top_questions = None,
                regenerated_requests = None,
                users_message_counts = None,
                top_documents = None,
        )
        """

    def testGetChatAnalyticsResponseMetrics(self):
        """Test GetChatAnalyticsResponseMetrics"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
