# coding: utf-8

"""
    API Docs

    API Documentation to interact with

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from odin_sdk.models.body_sync_document_to_knowledge_base_project_knowledge_sync_document_post import BodySyncDocumentToKnowledgeBaseProjectKnowledgeSyncDocumentPost

class TestBodySyncDocumentToKnowledgeBaseProjectKnowledgeSyncDocumentPost(unittest.TestCase):
    """BodySyncDocumentToKnowledgeBaseProjectKnowledgeSyncDocumentPost unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BodySyncDocumentToKnowledgeBaseProjectKnowledgeSyncDocumentPost:
        """Test BodySyncDocumentToKnowledgeBaseProjectKnowledgeSyncDocumentPost
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BodySyncDocumentToKnowledgeBaseProjectKnowledgeSyncDocumentPost`
        """
        model = BodySyncDocumentToKnowledgeBaseProjectKnowledgeSyncDocumentPost()
        if include_optional:
            return BodySyncDocumentToKnowledgeBaseProjectKnowledgeSyncDocumentPost(
                title = None,
                content = None,
                project_id = None,
                document_id = None
            )
        else:
            return BodySyncDocumentToKnowledgeBaseProjectKnowledgeSyncDocumentPost(
                title = None,
                content = None,
                project_id = None,
                document_id = None,
        )
        """

    def testBodySyncDocumentToKnowledgeBaseProjectKnowledgeSyncDocumentPost(self):
        """Test BodySyncDocumentToKnowledgeBaseProjectKnowledgeSyncDocumentPost"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
