# coding: utf-8

"""
    API Docs

    API Documentation to interact with

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from odin_sdk.models.generate_suggestions_request import GenerateSuggestionsRequest

class TestGenerateSuggestionsRequest(unittest.TestCase):
    """GenerateSuggestionsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GenerateSuggestionsRequest:
        """Test GenerateSuggestionsRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GenerateSuggestionsRequest`
        """
        model = GenerateSuggestionsRequest()
        if include_optional:
            return GenerateSuggestionsRequest(
                messages = [
                    odin_sdk.models.message.Message(
                        user = '', 
                        message = '', )
                    ],
                no_of_suggestions = 56,
                conversation_type = '',
                project_id = '',
                chat_id = '',
                model_name = 'gpt-4o-mini',
                system_prompt = None
            )
        else:
            return GenerateSuggestionsRequest(
                messages = [
                    odin_sdk.models.message.Message(
                        user = '', 
                        message = '', )
                    ],
                no_of_suggestions = 56,
                conversation_type = '',
                project_id = '',
                chat_id = '',
        )
        """

    def testGenerateSuggestionsRequest(self):
        """Test GenerateSuggestionsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
