def code():
    print('from sklearn.naive_bayes import GaussianNB')
    print('from sklearn.model_selection import train_test_split')
    print('import numpy as np')
    print('from sklearn.preprocessing import LabelEncoder')
    print('import pandas as pd')
    print('from sklearn.metrics import confusion_matrix,accuracy_score')
    print('')
    print("dataset=pd.read_csv('tennis.csv')")
    print('X=dataset.iloc[:,0:-1].copy()')
    print('y=dataset.iloc[:,-1]')
    print('')
    print('print("Data Before Encoding\\n",dataset.head())')
    print('print("Features Before Encoding\\n",X.head())')
    print('print("Target Before Encoding\\n",y.head())')
    print('')
    print('')
    print('label_encoder={}')
    print('')
    print('for column in X.columns:')
    print('    le=LabelEncoder()')
    print('    X[column]=le.fit_transform(X[column])')
    print('    label_encoder[column]=le')
    print('')
    print('print("Features After Encoding\\n",X.head())')
    print('')
    print('target_encoder=LabelEncoder()')
    print('y=target_encoder.fit_transform(y)')
    print('')
    print('')
    print('X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.30)')
    print('model=GaussianNB()')
    print('model.fit(X_train,y_train)')
    print('')
    print('y_pred=model.predict(X_test)')
    print('')
    print('print("Actual Label: ",y_test)')
    print('print("Predicted Label: ",y_pred)')
    print('print("Confusion Matrix: \\n",confusion_matrix(y_test,y_pred))')
    print('print("Accuracy Score: ",accuracy_score(y_test,y_pred)*100)')
