VersionReplace = "{{Version}}"
BuiltDateTimeReplace = "{{Built DateTime}}"
RanDateTimeReplace = "{{Ran DateTime}}"
BuildHashReplace = "{{Build Hash}}"
RanHashReplace = "{{Ran Hash}}"
AuthorReplace = "{{Authors}}"