class Cursor:
    JUMP = lambda x, y: f"\033[{y};{x}H"
    RIGHT = lambda num: f"\033[{num}C"
    DOWN = lambda num: f"\033[{num}B"
    LEFT = lambda num: f"\033[{num}D"
    UP = lambda num: f"\033[{num}F"
    CLEAR_LINE = "\033[2K\r"
    CLEAR_ALL = "\033c"
    HIDE = "\033[?25l"
    SHOW = "\033[?25h"
    SAVE = "\x1b[s"
    BACK = "\x1b[u"
    PRINT = lambda name: print(name, end="", flush=True)
    MODE_DEFAULT = "\033[0 q"
    MODE_THICK = "\033[2 q"
    MODE_BLINKING_THICK = "\033[1 q"
    MODE_BL = "\033[4 q"
    MODE_BLINKING_BL = "\033[3 q"
    MODE_BLINKING_CLASSIC = "\033[5 q"
    MODE_CLASSIC = "\033[6 q"
    CLEAR_TEXT = "\033[0m"
