ACCEPT_HEADER = 'Accept'
AUTHORIZATION_HEADER = 'Authorization'
CONTENT_TYPE_HEADER = 'Content-Type'
CLIENT_ID_HEADER = 'CE-ClientId'
ACCESS_TOKEN_HEADER = 'CE-AccessToken'

HTTP_METHOD_POST = 'POST'
HTTP_METHOD_GET = 'GET'
HTTP_METHOD_PATCH = 'PATCH'
HTTP_METHOD_DELETE = 'DELETE'
HTTP_METHOD_PUT = 'PUT'

JSON_CONTENT_TYPE = 'application/json'
TEXT_CONTENT_TYPE = 'text/html'
