# coding: utf-8

"""
    API Docs

    API Documentation to interact with

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from odin_sdk.models.subscription_update import SubscriptionUpdate

class TestSubscriptionUpdate(unittest.TestCase):
    """SubscriptionUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SubscriptionUpdate:
        """Test SubscriptionUpdate
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SubscriptionUpdate`
        """
        model = SubscriptionUpdate()
        if include_optional:
            return SubscriptionUpdate(
                user_id = None,
                number_of_seats = None
            )
        else:
            return SubscriptionUpdate(
                user_id = None,
                number_of_seats = None,
        )
        """

    def testSubscriptionUpdate(self):
        """Test SubscriptionUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
