# coding: utf-8

"""
    API Docs

    API Documentation to interact with

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from odin_sdk.models.toggleiconcolor import Toggleiconcolor

class TestToggleiconcolor(unittest.TestCase):
    """Toggleiconcolor unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Toggleiconcolor:
        """Test Toggleiconcolor
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Toggleiconcolor`
        """
        model = Toggleiconcolor()
        if include_optional:
            return Toggleiconcolor(
            )
        else:
            return Toggleiconcolor(
        )
        """

    def testToggleiconcolor(self):
        """Test Toggleiconcolor"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
