# coding: utf-8

"""
    API Docs

    API Documentation to interact with

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from odin_sdk.models.open_canvas_graph_annotation_artifact_length import OpenCanvasGraphAnnotationArtifactLength

class TestOpenCanvasGraphAnnotationArtifactLength(unittest.TestCase):
    """OpenCanvasGraphAnnotationArtifactLength unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OpenCanvasGraphAnnotationArtifactLength:
        """Test OpenCanvasGraphAnnotationArtifactLength
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OpenCanvasGraphAnnotationArtifactLength`
        """
        model = OpenCanvasGraphAnnotationArtifactLength()
        if include_optional:
            return OpenCanvasGraphAnnotationArtifactLength(
            )
        else:
            return OpenCanvasGraphAnnotationArtifactLength(
        )
        """

    def testOpenCanvasGraphAnnotationArtifactLength(self):
        """Test OpenCanvasGraphAnnotationArtifactLength"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
