# coding: utf-8

"""
    API Docs

    API Documentation to interact with

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from odin_sdk.models.get_documents_response import GetDocumentsResponse

class TestGetDocumentsResponse(unittest.TestCase):
    """GetDocumentsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetDocumentsResponse:
        """Test GetDocumentsResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetDocumentsResponse`
        """
        model = GetDocumentsResponse()
        if include_optional:
            return GetDocumentsResponse(
                message = None,
                documents = None
            )
        else:
            return GetDocumentsResponse(
                message = None,
                documents = None,
        )
        """

    def testGetDocumentsResponse(self):
        """Test GetDocumentsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
