DEFAULT_OWNER: str
GITHUB_PR_COMMITS_CACHE_KEY: str
AUTH_CACHE_KEY_FORMAT: str
GITHUB_PR_COMMITS_CACHE_TTL: int
AUTH_CACHE_TTL: int
GITHUB_PR_COMMITS_PROCESSING_VALUE: str
GITHUB_DATE_FORMAT: str
