def code():
    print('')
    print('')
    print('')
    print('#6. Write a program to implement k-Nearest Neighbor algorithm to classify the iris data set. Print both correct and wrong predictions. Java/Python ML library classes can be used for this problem.')
    print('')
    print('import numpy as np')
    print('from sklearn.model_selection import train_test_split')
    print('from sklearn.neighbors import KNeighborsClassifier')
    print('from sklearn.metrics import accuracy_score')
    print('from sklearn import datasets')
    print('')
    print('# Load the Iris dataset')
    print('iris = datasets.load_iris()')
    print('X = iris.data')
    print('y = iris.target')
    print('')
    print('# Split the dataset into 70% training and 30% testing')
    print('X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)')
    print('')
    print('# Create the KNN classifier with k=5 (you can change k as needed)')
    print('knn = KNeighborsClassifier(n_neighbors=5)')
    print('knn.fit(X_train, y_train)')
    print('')
    print('# Predict the classes for the test set')
    print('y_pred = knn.predict(X_test)')
    print('')
    print('# Print both correct and wrong predictions')
    print('print(f"{\'Index\':<5} {\'True Label\':<10} {\'Predicted\':<10} {\'Result\'}")')
    print("print('-' * 40)")
    print('for idx, (true, pred) in enumerate(zip(y_test, y_pred)):')
    print('    result = "Correct" if true == pred else "Wrong"')
    print('    print(f"{idx:<5} {true:<10} {pred:<10} {result}")')
    print('')
    print('# Optionally, print overall accuracy')
    print('print("\\nAccuracy:", accuracy_score(y_test, y_pred))')
