import datetime
from sinli.document import Document

def test_read_abono_v2():
  result = Document.from_filename("res/example-sinli-docs/ABONO/I6A1763")

  assert result.long_id_line.to_dict() == {
    "TYPE": "I",
    "FORMAT": "N",
    "DOCTYPE": "ABONO",
    "VERSION": "02",
    "FROM": "L0002956",
    "TO": "L1234567",
    "LEN": 0,
    "NUM_TRANS": 0,
    "LOCAL_FROM": "",
    "LOCAL_TO": "",
    "TEXT": "",
    "FANDE": "FANDE",
  }

  assert result.short_id_line.to_dict() == {
    "TYPE": "I",
    "FROM": "sinli.virus@zonalibros.com",
    "TO": "libreria@example.org",
    "DOCTYPE": "ABONO",
    "VERSION": "02",
    "TRANSMISION_NUMBER": 0,
  }

  assert [element.to_dict() for element in result.doc_lines] == [
    {
        "TYPE": "C",
        "PROVIDER": "VIRUS EDITORIAL I DISTRIBUIDORA SCCL",
        "CLIENT": "LIBRERIA DE EJEMPLO",
        "DELIVERY_NUM": "002001580",
        "DATE": datetime.date(2024, 4, 15),
        "INVOICE_OR_NOTE": ("A", "Albarán"),
        "DEVOLUTION_REFERENCE": "210",
        "DEVOLUTION_DATE": datetime.date(2024, 4, 15),
        "PAYMENT_TYPE": ("D", "Depósito"),
        "BOOK_FAIRE": False,
        "SHIPPING_COST": 0.0,
        "CURRENCY": "E",
    },
    {
      "TYPE": "D",
      "ISBN": "978-84-18723-24-7",
      "EAN": "9788418723247",
      "REF": "036000986",
      "TITLE": "LIU (CAST)",
      "AMOUNT": -7,
      "PRICE_NO_VAT": 17.31,
      "PRICE_W_VAT": 18.0,
      "DISCOUNT": 30.0,
      "VAT_PERCENT": 4.0,
      "NEW": False,
      "PRICE_TYPE": ("F", "Precio final fijo"),
    },
    {
      "TYPE": "D",
      "ISBN": "978-84-937671-0-5",
      "EAN": "9788493767105",
      "REF": "032000016",
      "TITLE": "INSTINTO DE MUERTE. La autobiografía",
      "AMOUNT": -1,
      "PRICE_NO_VAT": 21.15,
      "PRICE_W_VAT": 22.0,
      "DISCOUNT": 30.0,
      "VAT_PERCENT": 4.0,
      "NEW": False,
      "PRICE_TYPE": ("F", "Precio final fijo"),
    },
    {
      "TYPE": "D",
      "ISBN": "978-84-19160-58-4",
      "EAN": "9788419160584",
      "REF": "036001138",
      "TITLE": "NI PÚBLICO NI PRIVADO, ¿SINO COMÚN?",
      "AMOUNT": -1,
      "PRICE_NO_VAT": 21.15,
      "PRICE_W_VAT": 22.0,
      "DISCOUNT": 30.0,
      "VAT_PERCENT": 4.0,
      "NEW": False,
      "PRICE_TYPE": ("F", "Precio final fijo"),
    },
    {
      "TYPE": "D",
      "ISBN": "978-84-09-50305-6",
      "EAN": "9788409503056",
      "REF": "375000377",
      "TITLE": "RESURRECCIÓN DE LAS MONSTRUAS, LA",
      "AMOUNT": -2,
      "PRICE_NO_VAT": 13.46,
      "PRICE_W_VAT": 14.0,
      "DISCOUNT": 30.0,
      "VAT_PERCENT": 4.0,
      "NEW": False,
      "PRICE_TYPE": ("F", "Precio final fijo"),
    },
    {
      "TYPE": "D",
      "ISBN": "978-84-09-40544-2",
      "EAN": "9788409405442",
      "REF": "375000022",
      "TITLE": "ARMADAS CON LA PLUMA Y LA PALABRA",
      "AMOUNT": -2,
      "PRICE_NO_VAT": 13.46,
      "PRICE_W_VAT": 14.0,
      "DISCOUNT": 30.0,
      "VAT_PERCENT": 4.0,
      "NEW": False,
      "PRICE_TYPE": ("F", "Precio final fijo")
    },
    {
      "TYPE": "D",
      "ISBN": "978-84-09-35363-7",
      "EAN": "9788409353637",
      "REF": "375000375",
      "TITLE": "ACCION TRAVESTI CALLEJERA REVOLUCIONARIA (2ªed)",
      "AMOUNT": -1,
      "PRICE_NO_VAT": 9.62,
      "PRICE_W_VAT": 10.0,
      "DISCOUNT": 30.0,
      "VAT_PERCENT": 4.0,
      "NEW": False,
      "PRICE_TYPE": ("F", "Precio final fijo")
    },
    {
      "TYPE_REGISTER": "T",
      "TOTAL_UD": -14,
      "TOTAL_DOCUMENT": -165.2,
    },
    {
      "TYPE": "V",
      "VAT_PERCENTAGE": 4.0,
      "TAX_BASE": -158.85,
      "VAT": -6.35,
      "PERCENTAGE_REQ": 0.0,
      "REQ": 0.0,
    }
  ]