# coding: utf-8

"""
    API Docs

    API Documentation to interact with

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel
from odin_sdk.models.docs import Docs
from odin_sdk.models.entire_kb import EntireKb
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class SyncKBRequest(BaseModel):
    """
    SyncKBRequest
    """ # noqa: E501
    entire_kb: Optional[EntireKb] = None
    project_id: Optional[Any]
    docs: Optional[Docs] = None
    __properties: ClassVar[List[str]] = ["entire_kb", "project_id", "docs"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of SyncKBRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of entire_kb
        if self.entire_kb:
            _dict['entire_kb'] = self.entire_kb.to_dict()
        # override the default output from pydantic by calling `to_dict()` of docs
        if self.docs:
            _dict['docs'] = self.docs.to_dict()
        # set to None if project_id (nullable) is None
        # and model_fields_set contains the field
        if self.project_id is None and "project_id" in self.model_fields_set:
            _dict['project_id'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of SyncKBRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "entire_kb": EntireKb.from_dict(obj.get("entire_kb")) if obj.get("entire_kb") is not None else None,
            "project_id": obj.get("project_id"),
            "docs": Docs.from_dict(obj.get("docs")) if obj.get("docs") is not None else None
        })
        return _obj


