# coding: utf-8

"""
    Akrimanager Backend v2

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from akridata_akrimanager_v2.configuration import Configuration


class ViewUDFParam(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'name': 'str',
        'column_info': 'ViewUDFColumnInfo',
        'alias_info': 'ViewUDFAliasInfo',
        'constant_value': 'str'
    }

    attribute_map = {
        'name': 'name',
        'column_info': 'column_info',
        'alias_info': 'alias_info',
        'constant_value': 'constant_value'
    }

    def __init__(self, name=None, column_info=None, alias_info=None, constant_value=None, local_vars_configuration=None):  # noqa: E501
        """ViewUDFParam - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._name = None
        self._column_info = None
        self._alias_info = None
        self._constant_value = None
        self.discriminator = None

        self.name = name
        if column_info is not None:
            self.column_info = column_info
        if alias_info is not None:
            self.alias_info = alias_info
        if constant_value is not None:
            self.constant_value = constant_value

    @property
    def name(self):
        """Gets the name of this ViewUDFParam.  # noqa: E501


        :return: The name of this ViewUDFParam.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ViewUDFParam.


        :param name: The name of this ViewUDFParam.  # noqa: E501
        :type name: str
        """
        if self.local_vars_configuration.client_side_validation and name is None:  # noqa: E501
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def column_info(self):
        """Gets the column_info of this ViewUDFParam.  # noqa: E501


        :return: The column_info of this ViewUDFParam.  # noqa: E501
        :rtype: ViewUDFColumnInfo
        """
        return self._column_info

    @column_info.setter
    def column_info(self, column_info):
        """Sets the column_info of this ViewUDFParam.


        :param column_info: The column_info of this ViewUDFParam.  # noqa: E501
        :type column_info: ViewUDFColumnInfo
        """

        self._column_info = column_info

    @property
    def alias_info(self):
        """Gets the alias_info of this ViewUDFParam.  # noqa: E501


        :return: The alias_info of this ViewUDFParam.  # noqa: E501
        :rtype: ViewUDFAliasInfo
        """
        return self._alias_info

    @alias_info.setter
    def alias_info(self, alias_info):
        """Sets the alias_info of this ViewUDFParam.


        :param alias_info: The alias_info of this ViewUDFParam.  # noqa: E501
        :type alias_info: ViewUDFAliasInfo
        """

        self._alias_info = alias_info

    @property
    def constant_value(self):
        """Gets the constant_value of this ViewUDFParam.  # noqa: E501


        :return: The constant_value of this ViewUDFParam.  # noqa: E501
        :rtype: str
        """
        return self._constant_value

    @constant_value.setter
    def constant_value(self, constant_value):
        """Sets the constant_value of this ViewUDFParam.


        :param constant_value: The constant_value of this ViewUDFParam.  # noqa: E501
        :type constant_value: str
        """

        self._constant_value = constant_value

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ViewUDFParam):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ViewUDFParam):
            return True

        return self.to_dict() != other.to_dict()
