# coding: utf-8

"""
    aind-sharepoint-service

     ## aind-sharepoint-service  Service to pull data from Sharepoint.  

    The version of the OpenAPI document: 0.0.6
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aind_sharepoint_service_async_client.models.project_id import ProjectId

class TestProjectId(unittest.TestCase):
    """ProjectId unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProjectId(self):
        """Test ProjectId"""
        # inst = ProjectId()

if __name__ == '__main__':
    unittest.main()
