# coding: utf-8

"""
    aind-sharepoint-service

     ## aind-sharepoint-service  Service to pull data from Sharepoint.  

    The version of the OpenAPI document: 0.0.6
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class During2NdInjection(str, Enum):
    """
    Enum class for During2NdInjection
    """

    """
    allowed enum values
    """
    BLEEDING = 'Bleeding'
    BLEEDING_SLASH_FLUID_COMING_UP = 'Bleeding/Fluid coming up'
    FLUID_COMING_UP = 'Fluid coming up'
    N_SLASH_A = 'N/A'
    NO_ISSUES = 'No Issues'
    PIPETTE_CLOGGED_SLASH_BROKE_TIP = 'Pipette clogged/broke tip'
    SELECT_DOT_DOT_DOT = 'Select...'
    SWELLING = 'Swelling'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of During2NdInjection from a JSON string"""
        return cls(json.loads(json_str))


