# coding: utf-8

"""
    API Docs

    API Documentation to interact with

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from odin_sdk.models.odin_action_model import OdinActionModel

class TestOdinActionModel(unittest.TestCase):
    """OdinActionModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OdinActionModel:
        """Test OdinActionModel
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OdinActionModel`
        """
        model = OdinActionModel()
        if include_optional:
            return OdinActionModel(
                flow_id = None,
                action_name = None,
                action_description = None,
                required_fields_for_flow = None,
                autosend = None,
                type = None,
                config = None
            )
        else:
            return OdinActionModel(
                flow_id = None,
                action_name = None,
                action_description = None,
                autosend = None,
        )
        """

    def testOdinActionModel(self):
        """Test OdinActionModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
