# coding: utf-8

"""
    API Docs

    API Documentation to interact with

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from odin_sdk.models.team_info_details import TeamInfoDetails

class TestTeamInfoDetails(unittest.TestCase):
    """TeamInfoDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TeamInfoDetails:
        """Test TeamInfoDetails
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TeamInfoDetails`
        """
        model = TeamInfoDetails()
        if include_optional:
            return TeamInfoDetails(
                active = None,
                admin = None,
                name = None,
                credits = None,
                used_credits = None,
                bonus_credits = None,
                allowed_seats = None,
                team_id = None,
                members = None,
                email_domain = None,
                owner = None,
                plan_type = None,
                api_keys = None,
                settings = None,
                aihub_projects_whitelist = None
            )
        else:
            return TeamInfoDetails(
        )
        """

    def testTeamInfoDetails(self):
        """Test TeamInfoDetails"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
