# coding: utf-8

"""
    aind-sharepoint-service

     ## aind-sharepoint-service  Service to pull data from Sharepoint.  

    The version of the OpenAPI document: 0.0.6
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aind_sharepoint_service_client.models.aind_sharepoint_service_server_models_nsb2019_laceration import AindSharepointServiceServerModelsNsb2019Laceration

class TestAindSharepointServiceServerModelsNsb2019Laceration(unittest.TestCase):
    """AindSharepointServiceServerModelsNsb2019Laceration unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAindSharepointServiceServerModelsNsb2019Laceration(self):
        """Test AindSharepointServiceServerModelsNsb2019Laceration"""
        # inst = AindSharepointServiceServerModelsNsb2019Laceration()

if __name__ == '__main__':
    unittest.main()
