# coding: utf-8

"""
    aind-sharepoint-service

     ## aind-sharepoint-service  Service to pull data from Sharepoint.  

    The version of the OpenAPI document: 0.0.6
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aind_sharepoint_service_client.models.inj4_retsetting import Inj4Retsetting

class TestInj4Retsetting(unittest.TestCase):
    """Inj4Retsetting unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInj4Retsetting(self):
        """Test Inj4Retsetting"""
        # inst = Inj4Retsetting()

if __name__ == '__main__':
    unittest.main()
